import * as vscode from 'vscode';
import { createMessageConnection, MessageConnection } from 'vscode-jsonrpc';
import { BaseWebviewProvider } from './baseProvider';
import * as PlotsProtocol from '../rpc/webview/plots';
import * as SessionProtocol from '../rpc/webview/session';
import { CoreCommandIds, ViewIds, WorkbenchViewContainerCommands } from '../coreCommandIds';
import { RuntimeSession } from '../runtime/session';
import { SessionManager } from '../runtime/sessionManager';
import { PlotClientInstance, RenderedPlot, ZoomLevel } from '../runtime/PlotClientInstance';
import { StaticPlotClient } from '../runtime/staticPlotClient';
import { HtmlPlotClient } from '../runtime/htmlPlotClient';
import { PositronPlotsService } from '../runtime/positronPlotsService';
import { PlotSizingPolicyAuto } from '../runtime/sizingPolicyAuto';
import { PlotSizingPolicyCustom } from '../runtime/sizingPolicyCustom';
import { PlotSizingPolicyIntrinsic } from '../runtime/sizingPolicyIntrinsic';
import type { IPlotSize, IPositronPlotSizingPolicy } from '../runtime/sizingPolicy';
import { PlotRenderFormat, type PlotRenderSettings } from '../runtime/comms/positronPlotComm';
import { DarkFilter, HistoryPolicy, HistoryPosition, isZoomablePlotClient, type IPositronPlotClient } from '../runtime/positronPlots';
import { WebviewMessageReader, WebviewMessageWriter } from '../rpc/webview/transport';
import { PositronConsoleService } from '../services/console';
import {
    createSelectedPlotChangedPayload,
    serializePlotRecord,
    toPlotAddedParams,
    type SerializedPlotRecord,
} from './plotsPayload';
import { SessionSnapshotBuilder } from './sessionSnapshotBuilder';

interface PlotData {
    id: string;
    sessionId: string;           // Session that created this plot (multi-session support)
    kind: 'static' | 'dynamic' | 'html';
    data: string;                // Base64 encoded image data
    mimeType: string;
    width: number;
    height: number;
    pixelRatio: number;
    thumbnail?: string;          // Base64 encoded thumbnail
    htmlUri?: string;            // HTML preview URI for webview plots
    originUri?: string;          // Source file URI for plot origin metadata
    originRange?: {
        startLine: number;
        startCharacter: number;
        endLine: number;
        endCharacter: number;
    };
    name?: string;
    // Positron-compatible metadata fields
    code?: string;               // Code that generated this plot
    suggestedFileName?: string;  // Suggested filename for saving
    created: number;             // Timestamp when plot was created
    parentId?: string;           // Parent message/execution ID
    output_id?: string;          // Output ID for update_output handling (Positron pattern)
    languageId?: string;        // Runtime language id for code re-execution
    zoomLevel?: number;          // Plot-specific zoom level (Positron pattern)
    sizingPolicyId?: string;     // Plot-specific sizing policy (Positron pattern)
    customSize?: IPlotSize;      // Plot-specific custom size when policy is custom
    hasIntrinsicSize?: boolean;  // Whether intrinsic size is available for this plot
    renderVersion: number;       // Monotonic version for the last accepted rendered image
}

interface PlotsConnectionState {
    selectedPlotId: string | undefined;
    selectedSizingPolicyId: string;
    customSize: IPlotSize | undefined;
    lastViewport:
    | { width: number; height: number; pixelRatio: number; format: PlotRenderFormat }
    | undefined;
    lastRenderSettingsKey: string | undefined;
    isPrimaryConnection: boolean;
    followsServiceSelection: boolean;
    followsServiceSizing: boolean;
    /** Timeout handle for debouncing viewport-triggered render settings updates. */
    renderSettingsTimeout: ReturnType<typeof setTimeout> | undefined;
}

/**
 * Webview provider for the Plots sidebar view.
 * Displays plots generated by the R kernel.
 * 
 * Integrates with PlotClientInstance via RuntimeClientManager.
 */
export class PlotsViewProvider extends BaseWebviewProvider {
    private readonly _disposables: vscode.Disposable[] = [];
    private readonly _auxConnections = new Set<MessageConnection>();
    private readonly _auxCloseHandlers = new Map<MessageConnection, () => void>();
    private readonly _connectionStates = new Map<MessageConnection, PlotsConnectionState>();
    private readonly _readyConnections = new Set<MessageConnection>();
    private readonly _renderRequestConnection = new Map<string, MessageConnection>();
    private readonly _htmlClaimsByConnection = new Map<MessageConnection, Set<string>>();
    private readonly _sessionSnapshotBuilder: SessionSnapshotBuilder;
    private _plots = new Map<string, PlotData>();
    private _plotClients = new Map<string, PlotClientInstance>();
    private _pendingSessionInfoUpdate = false;

    constructor(
        extensionUri: vscode.Uri,
        outputChannel: vscode.LogOutputChannel,
        private readonly _sessionManager: SessionManager | undefined,
        private readonly _plotsService: PositronPlotsService,
        private readonly _consoleService: PositronConsoleService,
        getAdditionalLocalResourceRoots: () => readonly vscode.Uri[] = () => [],
    ) {
        super(extensionUri, outputChannel, getAdditionalLocalResourceRoots);
        this._sessionSnapshotBuilder = new SessionSnapshotBuilder(this._sessionManager);
        this._subscribeToPlotsServiceEvents();
        this._seedPlotsFromService();

        if (this._sessionManager) {
            this._disposables.push(
                this._sessionManager.onDidChangeForegroundSession(() => {
                    this._forEachConnectionEntry((_connection, state) => {
                        state.lastRenderSettingsKey = undefined;
                    });
                    this._sendSessionInfoUpdate();
                }),
                this._sessionManager.onDidUpdateSessionName(() => {
                    this._sendSessionInfoUpdate();
                }),
                this._sessionManager.onDidDeleteRuntimeSession(() => {
                    this._sendSessionInfoUpdate();
                }),
                this._sessionManager.onDidChangeSessionState(() => {
                    this._sendSessionInfoUpdate();
                }),
            );
        }

        this._disposables.push(
            new vscode.Disposable(() => {
                for (const state of this._connectionStates.values()) {
                    if (state.renderSettingsTimeout) {
                        clearTimeout(state.renderSettingsTimeout);
                    }
                }
                this._connectionStates.clear();
                this._readyConnections.clear();
                this._renderRequestConnection.clear();
                for (const [connection] of this._htmlClaimsByConnection) {
                    this._releaseAllHtmlClaimsForConnection(connection);
                }
                this._htmlClaimsByConnection.clear();
                this._auxConnections.clear();
                this._auxCloseHandlers.clear();
            })
        );
    }

    protected get _providerName(): string {
        return 'PlotsViewProvider';
    }

    /**
     * Attaches an additional webview connection that can use the plots RPC surface.
     * Used by editor-based plot gallery panels.
     */
    createAuxWebviewConnection(
        webview: vscode.Webview,
        onCloseRequested?: () => void
    ): vscode.Disposable {
        const reader = new WebviewMessageReader(webview);
        const writer = new WebviewMessageWriter(webview);
        const connection = createMessageConnection(reader, writer);

        if (onCloseRequested) {
            this._auxCloseHandlers.set(connection, onCloseRequested);
        }

        this._connectionStates.set(connection, this._createConnectionState(false));
        this._registerRpcHandlers(connection);
        connection.listen();
        this._auxConnections.add(connection);

        this.log('Attached auxiliary plots webview RPC connection', vscode.LogLevel.Debug);

        return new vscode.Disposable(() => {
            this._auxConnections.delete(connection);
            this._auxCloseHandlers.delete(connection);
            this._readyConnections.delete(connection);
            const state = this._connectionStates.get(connection);
            if (state?.renderSettingsTimeout) {
                clearTimeout(state.renderSettingsTimeout);
            }
            this._connectionStates.delete(connection);
            for (const [plotId, targetConnection] of this._renderRequestConnection.entries()) {
                if (targetConnection === connection) {
                    this._renderRequestConnection.delete(plotId);
                }
            }
            this._releaseAllHtmlClaimsForConnection(connection);
            connection.dispose();
            this.log('Detached auxiliary plots webview RPC connection', vscode.LogLevel.Debug);
        });
    }

    private _createConnectionState(followsServiceState: boolean): PlotsConnectionState {
        const selectedPlotId = this._plotsService.selectedPlotId;
        const selectedPlotData = selectedPlotId
            ? this._plots.get(selectedPlotId)
            : undefined;

        return {
            selectedPlotId,
            selectedSizingPolicyId: selectedPlotData?.sizingPolicyId ?? this._plotsService.selectedSizingPolicy.id,
            customSize: selectedPlotData?.customSize
                ? { ...selectedPlotData.customSize }
                : undefined,
            lastViewport: undefined,
            lastRenderSettingsKey: undefined,
            isPrimaryConnection: followsServiceState,
            followsServiceSelection: followsServiceState,
            followsServiceSizing: followsServiceState,
            renderSettingsTimeout: undefined,
        };
    }

    private _forEachConnectionEntry(
        callback: (connection: MessageConnection, state: PlotsConnectionState) => void,
    ): void {
        if (this._connection) {
            const state = this._connectionStates.get(this._connection);
            if (state) {
                callback(this._connection, state);
            }
        }
        for (const connection of this._auxConnections) {
            const state = this._connectionStates.get(connection);
            if (state) {
                callback(connection, state);
            }
        }
    }

    private _resolveHtmlPlotClient(plotId: string): HtmlPlotClient | undefined {
        const client = this._plotsService.positronPlotInstances.find(candidate => candidate.id === plotId);
        return client instanceof HtmlPlotClient ? client : undefined;
    }

    private _claimHtmlPlot(connection: MessageConnection, plotId: string): { success: boolean; error?: string } {
        const htmlClient = this._resolveHtmlPlotClient(plotId);
        if (!htmlClient) {
            return { success: false, error: 'HTML plot not found' };
        }

        htmlClient.claim(connection);

        let claims = this._htmlClaimsByConnection.get(connection);
        if (!claims) {
            claims = new Set<string>();
            this._htmlClaimsByConnection.set(connection, claims);
        }
        claims.add(plotId);

        return { success: true };
    }

    private _releaseHtmlPlot(connection: MessageConnection, plotId: string): { success: boolean; error?: string } {
        const htmlClient = this._resolveHtmlPlotClient(plotId);
        if (htmlClient) {
            htmlClient.release(connection);
        }

        const claims = this._htmlClaimsByConnection.get(connection);
        if (claims) {
            claims.delete(plotId);
            if (claims.size === 0) {
                this._htmlClaimsByConnection.delete(connection);
            }
        }

        return { success: true };
    }

    private _releaseAllHtmlClaimsForConnection(connection: MessageConnection): void {
        const claims = this._htmlClaimsByConnection.get(connection);
        if (!claims || claims.size === 0) {
            this._htmlClaimsByConnection.delete(connection);
            return;
        }

        for (const plotId of claims) {
            const htmlClient = this._resolveHtmlPlotClient(plotId);
            htmlClient?.release(connection);
        }

        this._htmlClaimsByConnection.delete(connection);
    }

    private _layoutHtmlPlot(plotId: string, width: number, height: number): void {
        if (width <= 0 || height <= 0) {
            return;
        }

        const htmlClient = this._resolveHtmlPlotClient(plotId);
        htmlClient?.layout(width, height);
    }

    private _isConnectionReady(connection: MessageConnection): boolean {
        return this._readyConnections.has(connection);
    }

    private _notifyConnections(
        method: any,
        params: unknown,
        predicate: (state: PlotsConnectionState, connection: MessageConnection) => boolean = () => true,
    ): void {
        this._forEachConnectionEntry((connection, state) => {
            if (predicate(state, connection) && this._isConnectionReady(connection)) {
                connection.sendNotification(method, params as any);
            }
        });
    }

    private _hasAnyConnections(): boolean {
        return this._readyConnections.size > 0;
    }

    /**
     * Subscribes to a session's events (multi-session support).
     * Session lifecycle is handled by PositronPlotsService; we only refresh session info.
     */
    subscribeToSession(session: RuntimeSession): void {
        void session;
        this._sendSessionInfoUpdate();
    }

    /**
     * Unsubscribes from a session's events.
     * Session lifecycle is handled by PositronPlotsService; we only refresh session info.
     */
    unsubscribeFromSession(sessionId: string): void {
        void sessionId;
        this._sendSessionInfoUpdate();
    }

    /**
     * Subscribes to PositronPlotsService events (Positron 1:1 pattern).
     * The service manages plots; the provider only bridges to the webview.
     */
    private _subscribeToPlotsServiceEvents(): void {
        this._disposables.push(
            this._plotsService.onDidEmitPlot((plot) => {
                this._handlePlotAddedFromService(plot);
            }),
            this._plotsService.onDidRemovePlot((plot) => {
                this._handlePlotRemovedFromService(plot);
            }),
            this._plotsService.onDidReplacePlots((plots) => {
                this._handlePlotsReplacedFromService(plots);
            }),
            this._plotsService.onDidChangeSizingPolicy((policy) => {
                const selectedPlotId = this._plotsService.selectedPlotId;
                const selectedPlot = selectedPlotId
                    ? this._plotClients.get(selectedPlotId)
                    : undefined;
                const customSize = policy instanceof PlotSizingPolicyCustom
                    ? this._cloneSize(policy.size)
                    : undefined;

                this._storeSizingForPlotId(selectedPlotId, policy.id, customSize);
                this._forEachConnectionEntry((_connection, state) => {
                    if (!state.followsServiceSizing) {
                        return;
                    }
                    state.selectedSizingPolicyId = policy.id;
                    state.customSize = customSize;
                    state.lastRenderSettingsKey = undefined;
                });
                this._notifyConnections(
                    PlotsProtocol.SizingPolicyChangedNotification.type,
                    {
                        plotId: selectedPlotId,
                        policyId: policy.id,
                        policyName: policy.getName(selectedPlot as any),
                        policies: this._getSizingPoliciesPayloadForPlot(selectedPlot),
                        customSize,
                    },
                    state => state.followsServiceSizing
                );
            }),
            this._plotsService.onDidSelectPlot((plotId) => {
                const selectedPlot = plotId
                    ? this._plotClients.get(plotId)
                    : undefined;
                const sizingState = this._getSizingStateForPlotId(plotId || undefined);
                const selectedPlotChangedPayload = this._createSelectedPlotChangedPayload({
                    plotId: plotId || undefined,
                    selectedSizingPolicyId: sizingState.policyId,
                    sizingPolicies: this._getSizingPoliciesPayloadForPlot(selectedPlot),
                    customSize: this._cloneSize(sizingState.customSize),
                    hasIntrinsicSize: sizingState.hasIntrinsicSize ?? false,
                    zoomLevel: this._getZoomLevelForPlotId(plotId || undefined),
                });

                this._forEachConnectionEntry((_connection, state) => {
                    if (!state.followsServiceSelection) {
                        return;
                    }
                    state.selectedPlotId = plotId || undefined;
                    if (state.followsServiceSizing) {
                        this._refreshConnectionSizingStateFromSelectedPlot(state);
                    }
                });

                this._notifyConnections(
                    PlotsProtocol.SelectedPlotChangedNotification.type,
                    selectedPlotChangedPayload,
                    state => state.followsServiceSelection
                );

                const selectedPolicy = this._getSizingPolicyForConnection({
                    selectedPlotId: plotId || undefined,
                    selectedSizingPolicyId: sizingState.policyId,
                    customSize: sizingState.customSize,
                    lastViewport: undefined,
                    lastRenderSettingsKey: undefined,
                    isPrimaryConnection: true,
                    followsServiceSelection: true,
                    followsServiceSizing: true,
                    renderSettingsTimeout: undefined,
                });

                this._forEachConnectionEntry((_connection, state) => {
                    if (!state.followsServiceSizing) {
                        return;
                    }
                    state.selectedSizingPolicyId = sizingState.policyId;
                    state.customSize = this._cloneSize(sizingState.customSize);
                    state.lastRenderSettingsKey = undefined;
                });

                this._notifyConnections(
                    PlotsProtocol.SizingPolicyChangedNotification.type,
                    {
                        plotId: plotId || undefined,
                        policyId: sizingState.policyId,
                        policyName: selectedPolicy.getName(selectedPlot as any),
                        policies: this._getSizingPoliciesPayloadForPlot(selectedPlot),
                        customSize: this._cloneSize(sizingState.customSize),
                    },
                    state => state.followsServiceSizing
                );
            }),
            this._plotsService.onDidChangeHistoryPolicy((policy) => {
                this._notifyConnections(PlotsProtocol.HistoryPolicyChangedNotification.type, { policy });
            }),
            this._plotsService.onDidChangeHistoryPosition((position) => {
                this._notifyConnections(PlotsProtocol.HistoryPositionChangedNotification.type, { position });
            }),
            this._plotsService.onDidChangeDarkFilterMode((mode) => {
                this._notifyConnections(PlotsProtocol.DarkFilterModeChangedNotification.type, { mode });
            })
        );
    }

    private _cloneSize(size: IPlotSize | undefined): IPlotSize | undefined {
        if (!size) {
            return undefined;
        }

        return {
            width: size.width,
            height: size.height,
        };
    }

    private _getSizingStateForPlotId(plotId: string | undefined): {
        policyId: string;
        customSize: IPlotSize | undefined;
        hasIntrinsicSize: boolean | undefined;
    } {
        if (!plotId) {
            const policy = this._plotsService.selectedSizingPolicy;
            return {
                policyId: policy.id,
                customSize: policy instanceof PlotSizingPolicyCustom
                    ? this._cloneSize(policy.size)
                    : undefined,
                hasIntrinsicSize: false,
            };
        }

        const plotData = this._plots.get(plotId);
        if (plotData) {
            return {
                policyId: plotData.sizingPolicyId ?? this._plotsService.selectedSizingPolicy.id,
                customSize: this._cloneSize(plotData.customSize),
                hasIntrinsicSize: plotData.hasIntrinsicSize,
            };
        }

        const plotClient = this._plotClients.get(plotId);
        if (plotClient) {
            const policy = plotClient.sizingPolicy;
            return {
                policyId: policy.id,
                customSize: policy instanceof PlotSizingPolicyCustom
                    ? this._cloneSize(policy.size)
                    : undefined,
                hasIntrinsicSize: plotClient.receivedIntrinsicSize
                    ? !!plotClient.intrinsicSize
                    : undefined,
            };
        }

        const fallbackPolicy = this._plotsService.selectedSizingPolicy;
        return {
            policyId: fallbackPolicy.id,
            customSize: fallbackPolicy instanceof PlotSizingPolicyCustom
                ? this._cloneSize(fallbackPolicy.size)
                : undefined,
            hasIntrinsicSize: undefined,
        };
    }

    private _storeSizingForPlotId(
        plotId: string | undefined,
        policyId: string,
        customSize: IPlotSize | undefined,
    ): void {
        if (!plotId) {
            return;
        }

        const plotData = this._plots.get(plotId);
        if (plotData) {
            plotData.sizingPolicyId = policyId;
            plotData.customSize = this._cloneSize(policyId === 'custom' ? customSize : undefined);
            this._plots.set(plotId, plotData);
        }

        const plotClient = this._plotsService.positronPlotInstances.find(plot => plot.id === plotId);
        if (plotClient && !(plotClient instanceof PlotClientInstance)) {
            plotClient.metadata.sizing_policy = {
                id: policyId,
                size: policyId === 'custom'
                    ? this._cloneSize(customSize)
                    : undefined,
            };
        }
    }

    private _getSizingPolicyForConnection(state: PlotsConnectionState): IPositronPlotSizingPolicy {
        if (state.selectedSizingPolicyId === 'custom' && state.customSize) {
            return new PlotSizingPolicyCustom(state.customSize);
        }

        return this._plotsService.sizingPolicies.find(p => p.id === state.selectedSizingPolicyId)
            ?? this._plotsService.selectedSizingPolicy;
    }

    private _getSelectedPlotForConnection(state: PlotsConnectionState): PlotClientInstance | undefined {
        const plotId = state.selectedPlotId;
        return plotId ? this._plotClients.get(plotId) : undefined;
    }

    private _getZoomLevelForPlotId(plotId: string | undefined): number {
        if (!plotId) {
            return ZoomLevel.Fit;
        }

        return this._plots.get(plotId)?.zoomLevel ?? ZoomLevel.Fit;
    }

    private _getStateForConnection(connection: MessageConnection): PlotsConnectionState {
        const state = this._connectionStates.get(connection);
        if (!state) {
            throw new Error('Missing plots connection state');
        }
        return state;
    }

    private _sendSessionInfoUpdateToConnection(connection: MessageConnection): void {
        connection.sendNotification('session/info', this._buildSessionInfoSnapshot());
    }

    private _buildSessionInfoSnapshot(): SessionProtocol.SessionInfoNotification.Params {
        const sessions = this._sessionSnapshotBuilder.buildBaseSessions();

        return {
            sessions,
            activeSessionId: this._sessionSnapshotBuilder.resolveActiveSessionId(sessions, [
                this._sessionManager?.activeSessionId,
            ]),
        };
    }

    private _seedPlotsFromService(): void {
        for (const plot of this._plotsService.positronPlotInstances) {
            if (this._plots.has(plot.id)) {
                continue;
            }

            const plotData = this._createPlotDataFromClient(plot);
            if (!plotData.sessionId) {
                this.log(`Dropping plot ${plotData.id} without sessionId`, vscode.LogLevel.Debug);
                continue;
            }
            this._plots.set(plotData.id, plotData);
            if (plot instanceof PlotClientInstance) {
                this._plotClients.set(plot.id, plot);
                this._wirePlotClientEvents(plot, plotData.sessionId);
            }
        }
    }

    private _handlePlotAddedFromService(plot: IPositronPlotClient): void {
        const plotData = this._createPlotDataFromClient(plot);
        if (!plotData.sessionId) {
            this.log(`Dropping plot ${plotData.id} without sessionId`, vscode.LogLevel.Debug);
            return;
        }
        this._plots.set(plotData.id, plotData);

        // Track dynamic plot clients for render requests
        if (plot instanceof PlotClientInstance) {
            this._plotClients.set(plot.id, plot);
            this._wirePlotClientEvents(plot, plotData.sessionId);
        }

        this._forEachConnectionEntry((_connection, state) => {
            if (state.followsServiceSelection) {
                state.selectedPlotId = plotData.id;
            }
        });

        this.sendPlotAdded(plotData);
    }

    private _handlePlotRemovedFromService(plot: IPositronPlotClient): void {
        const existing = this._plots.get(plot.id);
        if (existing) {
            this._plots.delete(plot.id);
            this._plotClients.delete(plot.id);
            for (const [plotId] of this._renderRequestConnection.entries()) {
                if (plotId === plot.id) {
                    this._renderRequestConnection.delete(plotId);
                }
            }
            for (const [connection, claims] of this._htmlClaimsByConnection.entries()) {
                claims.delete(plot.id);
                if (claims.size === 0) {
                    this._htmlClaimsByConnection.delete(connection);
                }
            }
            this._notifyConnections('plots/removed', { plotIds: [plot.id], sessionId: existing.sessionId });
        }
    }

    private _handlePlotsReplacedFromService(plots: IPositronPlotClient[]): void {
        for (const [connection] of this._htmlClaimsByConnection) {
            this._releaseAllHtmlClaimsForConnection(connection);
        }
        this._plots.clear();
        this._plotClients.clear();
        this._renderRequestConnection.clear();

        for (const plot of plots) {
            const plotData = this._createPlotDataFromClient(plot);
            if (!plotData.sessionId) {
                this.log(`Dropping plot ${plotData.id} without sessionId`, vscode.LogLevel.Debug);
                continue;
            }
            this._plots.set(plotData.id, plotData);
            if (plot instanceof PlotClientInstance) {
                this._plotClients.set(plot.id, plot);
                this._wirePlotClientEvents(plot, plotData.sessionId);
            }
        }

        this._notifyConnections('plots/cleared', {});
        for (const plot of this._plots.values()) {
            this.sendPlotAdded(plot);
        }
    }

    private _shouldSendInlineImagePayload(plot: Pick<PlotData, 'kind'>): boolean {
        // Keep static-image behavior (no render request required), but avoid
        // pushing large dynamic image payloads during plot creation/list sync.
        return plot.kind === 'static';
    }

    private _getThumbnailForTransport(plot: Pick<PlotData, 'kind' | 'thumbnail'>): string | undefined {
        if (!this._shouldSendInlineImagePayload(plot)) {
            return undefined;
        }
        return plot.thumbnail;
    }

    private _getInitialDataForTransport(plot: Pick<PlotData, 'kind' | 'data' | 'thumbnail'>): string | undefined {
        if (!this._shouldSendInlineImagePayload(plot)) {
            return undefined;
        }

        if (!plot.data) {
            return undefined;
        }

        if (plot.thumbnail && plot.thumbnail === plot.data) {
            return undefined;
        }

        return plot.data;
    }

    private _getInitialRenderSettingsForTransport(
        plot: Pick<PlotData, 'kind' | 'width' | 'height' | 'pixelRatio' | 'data'>,
    ): { width: number; height: number; pixelRatio: number } | undefined {
        if (plot.kind !== 'dynamic' || !plot.data) {
            return undefined;
        }

        if (plot.width <= 0 || plot.height <= 0) {
            return undefined;
        }

        return {
            width: Math.floor(plot.width),
            height: Math.floor(plot.height),
            pixelRatio: plot.pixelRatio > 0 ? plot.pixelRatio : 1,
        };
    }

    private _serializePlot(plot: PlotData): SerializedPlotRecord {
        return serializePlotRecord(
            {
                id: plot.id,
                renderVersion: plot.renderVersion,
                sessionId: plot.sessionId,
                kind: plot.kind,
                htmlUri: plot.htmlUri,
                originUri: plot.originUri,
                name: plot.name,
                code: plot.code,
                parentId: plot.parentId,
                languageId: plot.languageId,
                zoomLevel: plot.zoomLevel,
                sizingPolicyId: plot.sizingPolicyId,
                customSize: plot.customSize,
                hasIntrinsicSize: plot.hasIntrinsicSize,
            },
            {
                thumbnail: this._getThumbnailForTransport(plot),
                initialData: this._getInitialDataForTransport(plot),
                initialRenderSettings: this._getInitialRenderSettingsForTransport(plot),
            },
        );
    }

    private _createSelectedPlotChangedPayload(input: {
        plotId: string | undefined;
        selectedSizingPolicyId: string;
        sizingPolicies: PlotsProtocol.SizingPolicyInfo[];
        customSize: IPlotSize | undefined;
        hasIntrinsicSize: boolean | undefined;
        zoomLevel: number;
    }): PlotsProtocol.SelectedPlotChangedNotification.Params {
        return createSelectedPlotChangedPayload({
            plotId: input.plotId,
            selectedSizingPolicyId: input.selectedSizingPolicyId,
            sizingPolicies: input.sizingPolicies,
            customSize: input.customSize,
            hasIntrinsicSize: input.hasIntrinsicSize,
            zoomLevel: input.zoomLevel,
        });
    }

    private _createSelectedPlotChangedPayloadForState(
        state: PlotsConnectionState,
    ): PlotsProtocol.SelectedPlotChangedNotification.Params {
        const selectedPolicy = this._getSizingPolicyForConnection(state);
        const sizingState = this._getSizingStateForPlotId(state.selectedPlotId);
        return this._createSelectedPlotChangedPayload({
            plotId: state.selectedPlotId,
            selectedSizingPolicyId: selectedPolicy.id,
            sizingPolicies: this._getSizingPoliciesPayload(state),
            customSize: selectedPolicy instanceof PlotSizingPolicyCustom
                ? this._cloneSize(selectedPolicy.size)
                : undefined,
            hasIntrinsicSize: sizingState.hasIntrinsicSize ?? false,
            zoomLevel: this._getZoomLevelForPlotId(state.selectedPlotId),
        });
    }

    private _applyRenderedPlot(plotId: string, rendered: RenderedPlot): PlotData | undefined {
        const plot = this._plots.get(plotId);
        if (!plot) {
            return undefined;
        }

        const nextUri = rendered.uri;
        const changedImage = plot.data !== nextUri || plot.thumbnail !== nextUri;

        plot.data = nextUri;
        if (rendered.size) {
            plot.width = rendered.size.width;
            plot.height = rendered.size.height;
        }
        plot.pixelRatio = rendered.pixel_ratio > 0 ? rendered.pixel_ratio : plot.pixelRatio;
        plot.thumbnail = nextUri;
        if (changedImage) {
            plot.renderVersion += 1;
        }

        this._plots.set(plotId, plot);
        return plot;
    }

    private _createPlotDataFromClient(plot: IPositronPlotClient): PlotData {
        const metadata = plot.metadata;
        const sessionId = metadata.session_id;
        const created = metadata.created ?? Date.now();

        let data = '';
        let mimeType = 'image/png';
        let kind: PlotData['kind'] = 'static';
        let width = 0;
        let height = 0;
        let pixelRatio = 1;
        let thumbnail: string | undefined;
        let htmlUri: string | undefined;

        // Positron pattern: start from cached thumbnail when available.
        thumbnail = this._plotsService.getCachedPlotThumbnailURI(plot.id);

        if (plot instanceof PlotClientInstance) {
            kind = 'dynamic';
            const lastRender = plot.lastRender;
            if (lastRender?.uri) {
                data = lastRender.uri;
                thumbnail = lastRender.uri;
                if (lastRender.size) {
                    width = lastRender.size.width;
                    height = lastRender.size.height;
                }
                pixelRatio = lastRender.pixel_ratio > 0 ? lastRender.pixel_ratio : 1;
            }
        } else if (plot instanceof StaticPlotClient) {
            kind = 'static';
            data = plot.uri;
            thumbnail = plot.uri;
            mimeType = plot.mimeType;
        } else if (plot instanceof HtmlPlotClient) {
            kind = 'html';
            htmlUri = plot.uri.toString();
            mimeType = 'text/html';
        }

        const sizingPolicyId = metadata.sizing_policy?.id ?? this._plotsService.selectedSizingPolicy.id;
        const customSize = sizingPolicyId === 'custom'
            ? this._cloneSize(metadata.sizing_policy?.size)
            : undefined;
        const hasIntrinsicSize = plot instanceof PlotClientInstance
            ? (plot.receivedIntrinsicSize ? !!plot.intrinsicSize : undefined)
            : false;

        return {
            id: plot.id,
            sessionId,
            kind,
            data,
            mimeType,
            width,
            height,
            pixelRatio,
            thumbnail,
            htmlUri,
            originUri: metadata.origin?.uri,
            originRange: metadata.origin?.range
                ? {
                    startLine: metadata.origin.range.start_line,
                    startCharacter: metadata.origin.range.start_character,
                    endLine: metadata.origin.range.end_line,
                    endCharacter: metadata.origin.range.end_character,
                }
                : undefined,
            name: metadata.name,
            code: metadata.code,
            suggestedFileName: metadata.suggested_file_name,
            created,
            parentId: metadata.execution_id,
            output_id: metadata.output_id,
            languageId: metadata.language,
            zoomLevel: isZoomablePlotClient(plot)
                ? plot.zoomLevel
                : (metadata.zoom_level ?? ZoomLevel.Fit),
            sizingPolicyId,
            customSize,
            hasIntrinsicSize,
            renderVersion: data || thumbnail ? 1 : 0,
        };
    }

    private _refreshConnectionSizingStateFromSelectedPlot(state: PlotsConnectionState): void {
        const sizingState = this._getSizingStateForPlotId(state.selectedPlotId);
        state.selectedSizingPolicyId = sizingState.policyId;
        state.customSize = this._cloneSize(sizingState.customSize);
    }

    private _wirePlotClientEvents(plotClient: PlotClientInstance, sessionId: string): void {
        this._disposables.push(
            plotClient.onDidRenderPlot((rendered: RenderedPlot) => {
                this._applyRenderedPlot(plotClient.id, rendered);
            }),
            plotClient.onDidCompleteRender((rendered) => {
                const plot = this._applyRenderedPlot(plotClient.id, rendered);
                const renderVersion = plot?.renderVersion ?? 0;
                const targetConnection = this._renderRequestConnection.get(plotClient.id);
                const notifiedConnections = new Set<MessageConnection>();
                const payload = {
                    plotId: plotClient.id,
                    uri: rendered.uri,
                    renderTimeMs: rendered.renderTimeMs,
                    renderVersion,
                };

                if (targetConnection && this._isConnectionReady(targetConnection)) {
                    targetConnection.sendNotification(
                        PlotsProtocol.PlotRenderCompletedNotification.type,
                        payload,
                    );
                    notifiedConnections.add(targetConnection);
                }

                this._forEachConnectionEntry((connection, state) => {
                    if (
                        state.selectedPlotId === plotClient.id &&
                        this._isConnectionReady(connection) &&
                        !notifiedConnections.has(connection)
                    ) {
                        connection.sendNotification(
                            PlotsProtocol.PlotRenderCompletedNotification.type,
                            payload,
                        );
                    }
                });
            }),
            plotClient.onDidClose(() => {
                this._plotClients.delete(plotClient.id);
            }),
            plotClient.onDidChangeZoomLevel((zoomLevel) => {
                const plot = this._plots.get(plotClient.id);
                if (plot) {
                    plot.zoomLevel = zoomLevel;
                    this._plots.set(plotClient.id, plot);
                }

                this._notifyConnections(
                    PlotsProtocol.PlotZoomChangedNotification.type,
                    { plotId: plotClient.id, zoomLevel }
                );

                const selectedPlotId = this._plotsService.selectedPlotId;
                if (selectedPlotId === plotClient.id) {
                    const sizingState = this._getSizingStateForPlotId(plotClient.id);
                    const payload = this._createSelectedPlotChangedPayload({
                        plotId: plotClient.id,
                        selectedSizingPolicyId: sizingState.policyId,
                        sizingPolicies: this._getSizingPoliciesPayloadForPlot(plotClient),
                        customSize: this._cloneSize(sizingState.customSize),
                        hasIntrinsicSize: sizingState.hasIntrinsicSize,
                        zoomLevel,
                    });
                    this._notifyConnections(
                        PlotsProtocol.SelectedPlotChangedNotification.type,
                        payload,
                        state => state.followsServiceSelection,
                    );
                }
            }),
            plotClient.onDidChangeSizingPolicy((policy) => {
                const customSize = policy instanceof PlotSizingPolicyCustom
                    ? this._cloneSize(policy.size)
                    : undefined;

                this._storeSizingForPlotId(plotClient.id, policy.id, customSize);

                const selectedPlotId = this._plotsService.selectedPlotId;
                if (selectedPlotId === plotClient.id) {
                    this._forEachConnectionEntry((_connection, state) => {
                        if (!state.followsServiceSizing) {
                            return;
                        }
                        state.selectedSizingPolicyId = policy.id;
                        state.customSize = this._cloneSize(customSize);
                        state.lastRenderSettingsKey = undefined;
                    });

                    this._notifyConnections(
                        PlotsProtocol.SizingPolicyChangedNotification.type,
                        {
                            plotId: plotClient.id,
                            policyId: policy.id,
                            policyName: policy.getName(plotClient),
                            policies: this._getSizingPoliciesPayloadForPlot(plotClient),
                            customSize: this._cloneSize(customSize),
                        },
                        state => state.followsServiceSizing,
                    );

                    this._notifyConnections(
                        PlotsProtocol.SelectedPlotChangedNotification.type,
                        this._createSelectedPlotChangedPayload({
                            plotId: plotClient.id,
                            selectedSizingPolicyId: policy.id,
                            sizingPolicies: this._getSizingPoliciesPayloadForPlot(plotClient),
                            customSize: this._cloneSize(customSize),
                            hasIntrinsicSize: plotClient.receivedIntrinsicSize
                                ? !!plotClient.intrinsicSize
                                : undefined,
                            zoomLevel: this._getZoomLevelForPlotId(plotClient.id),
                        }),
                        state => state.followsServiceSelection,
                    );
                }
            }),
            plotClient.onDidSetIntrinsicSize((size) => {
                const plot = this._plots.get(plotClient.id);
                if (plot) {
                    plot.hasIntrinsicSize = !!size;
                    this._plots.set(plotClient.id, plot);
                }

                const selectedPlotId = this._plotsService.selectedPlotId;
                if (selectedPlotId === plotClient.id) {
                    const sizingState = this._getSizingStateForPlotId(plotClient.id);
                    this._notifyConnections(
                        PlotsProtocol.SelectedPlotChangedNotification.type,
                        this._createSelectedPlotChangedPayload({
                            plotId: plotClient.id,
                            selectedSizingPolicyId: sizingState.policyId,
                            sizingPolicies: this._getSizingPoliciesPayloadForPlot(plotClient),
                            customSize: this._cloneSize(sizingState.customSize),
                            hasIntrinsicSize: !!size,
                            zoomLevel: this._getZoomLevelForPlotId(plotClient.id),
                        }),
                        state => state.followsServiceSelection,
                    );
                }
            }),
            plotClient.onDidUpdateMetadata((metadata) => {
                const plot = this._plots.get(plotClient.id);
                if (plot) {
                    plot.name = metadata.name;
                    plot.code = metadata.code;
                    plot.suggestedFileName = metadata.suggested_file_name;
                    plot.languageId = metadata.language;
                    plot.originUri = metadata.origin?.uri;
                    plot.originRange = metadata.origin?.range
                        ? {
                            startLine: metadata.origin.range.start_line,
                            startCharacter: metadata.origin.range.start_character,
                            endLine: metadata.origin.range.end_line,
                            endCharacter: metadata.origin.range.end_character,
                        }
                        : undefined;
                    this._plots.set(plotClient.id, plot);
                    this._notifyConnections(
                        PlotsProtocol.PlotUpdatedNotification.type,
                        {
                            plotId: plotClient.id,
                            name: metadata.name,
                            code: metadata.code,
                            parentId: metadata.execution_id,
                            languageId: metadata.language,
                            originUri: metadata.origin?.uri,
                        }
                    );
                }
            })
        );
    }

    private _sendSessionInfoUpdate(): void {
        if (!this._hasAnyConnections()) {
            this._pendingSessionInfoUpdate = true;
            return;
        }

        let hasBlockedConnection = false;
        this._forEachConnectionEntry((connection) => {
            if (!this._isConnectionReady(connection)) {
                hasBlockedConnection = true;
                return;
            }
            this._sendSessionInfoUpdateToConnection(connection);
        });
        this._pendingSessionInfoUpdate = hasBlockedConnection;
    }

    protected _registerRpcHandlers(connection: MessageConnection): void {
        if (!this._connectionStates.has(connection)) {
            const followsServiceState = connection === this._connection;
            this._connectionStates.set(connection, this._createConnectionState(followsServiceState));
        }

        if (!this._htmlClaimsByConnection.has(connection)) {
            this._htmlClaimsByConnection.set(connection, new Set<string>());
        }

        this._readyConnections.delete(connection);

        connection.onClose(() => {
            this._releaseAllHtmlClaimsForConnection(connection);
            this._readyConnections.delete(connection);
        });

        connection.onNotification(PlotsProtocol.PlotsReadyNotification.type, () => {
            this.log('Received plots/ready from webview', vscode.LogLevel.Debug);
            this._readyConnections.add(connection);
            this._flushPendingPlotsSync(connection);
        });

        const state = this._getStateForConnection(connection);
        if (state.followsServiceSelection) {
            state.selectedPlotId = this._plotsService.selectedPlotId;
        }
        if (state.followsServiceSizing) {
            this._refreshConnectionSizingStateFromSelectedPlot(state);
        }
        this._sendSessionInfoUpdateToConnection(connection);
        if (this._isConnectionReady(connection)) {
            connection.sendNotification(PlotsProtocol.HistoryPolicyChangedNotification.type, {
                policy: this._plotsService.historyPolicy
            });
            connection.sendNotification(PlotsProtocol.HistoryPositionChangedNotification.type, {
                position: this._plotsService.historyPosition
            });
        }

        // Handle session/list request - provides activeSessionId to webview
        connection.onRequest('session/list', async () => {
            return this._buildSessionInfoSnapshot();
        });

        connection.onRequest(PlotsProtocol.GetHistoryStateRequest.type, async () => {
            return {
                policy: this._plotsService.historyPolicy,
                position: this._plotsService.historyPosition,
            };
        });

        connection.onRequest(PlotsProtocol.GetDarkFilterModeRequest.type, async () => {
            return { mode: this._plotsService.darkFilterMode };
        });

        connection.onRequest('plots/getPreferredEditorTarget', async () => {
            return { target: this._plotsService.getPreferredEditorTarget() };
        });

        connection.onRequest(PlotsProtocol.SelectDarkFilterModeRequest.type, async (params) => {
            this._plotsService.setDarkFilterMode(params.mode as DarkFilter);
        });

        connection.onRequest(PlotsProtocol.ClaimHtmlPlotRequest.type, async (params) => {
            return this._claimHtmlPlot(connection, params.plotId);
        });

        connection.onRequest(PlotsProtocol.ReleaseHtmlPlotRequest.type, async (params) => {
            return this._releaseHtmlPlot(connection, params.plotId);
        });

        connection.onNotification(PlotsProtocol.HtmlPlotLayoutNotification.type, (params) => {
            this._layoutHtmlPlot(params.plotId, params.width, params.height);
        });

        // Track viewport size changes from the webview for pre-render settings.
        // Debounce to avoid flooding the R graphics device during continuous resize.
        connection.onNotification(
            PlotsProtocol.PlotViewportChangedNotification.type,
            (params) => {
                const state = this._getStateForConnection(connection);
                const width = Math.floor(params.width);
                const height = Math.floor(params.height);
                if (width <= 0 || height <= 0) {
                    return;
                }

                state.lastViewport = {
                    width,
                    height,
                    pixelRatio: params.pixelRatio > 0 ? params.pixelRatio : 1,
                    format: params.format === 'svg' ? PlotRenderFormat.Svg : PlotRenderFormat.Png
                };
                if (state.followsServiceSizing) {
                    this._scheduleSendRenderSettings(state);
                }
            }
        );

        // Handle render plot request
        connection.onRequest(PlotsProtocol.RenderPlotRequest.type, async (params) => {
            this.log(`Render plot ${params.plotId} at ${params.width}x${params.height}`, vscode.LogLevel.Debug);
            this._renderRequestConnection.set(params.plotId, connection);
            try {
                const state = this._getStateForConnection(connection);

                // First check if we have a PlotClientInstance (for dynamic re-rendering)
                const plotClient = this._plotClients.get(params.plotId);
                if (plotClient) {
                    try {
                        const viewportSize = { width: params.width, height: params.height };
                        const pixelRatio = params.pixelRatio ?? 2;
                        const format = params.format === 'svg' ? PlotRenderFormat.Svg : PlotRenderFormat.Png;
                        let policy = this._getSizingPolicyForConnection(state);
                        if (policy instanceof PlotSizingPolicyIntrinsic) {
                            policy = new PlotSizingPolicyAuto();
                        }
                        const targetSize = policy.getPlotSize(viewportSize) ?? viewportSize;

                        const rendered = await plotClient.renderPlot(
                            {
                                width: Math.floor(targetSize.width),
                                height: Math.floor(targetSize.height)
                            },
                            pixelRatio,
                            format,
                            true  // Suppress completeRenderEmitter — RPC response already carries the data URI
                        );

                        const plot = this._applyRenderedPlot(params.plotId, rendered);

                        return {
                            data: rendered.uri,
                            mimeType: 'image/png',
                            renderVersion: plot?.renderVersion ?? 0,
                        };
                    } catch (e) {
                        this.log(`Failed to re-render plot ${params.plotId}: ${e}`, vscode.LogLevel.Warning);
                        // Fall through to return cached data
                    }
                }

                // Fallback to stored data
                const plot = this._plots.get(params.plotId);
                if (plot) {
                    // Update stored dimensions
                    plot.width = params.width;
                    plot.height = params.height;

                    if (plot.kind === 'html') {
                        return {
                            data: '',
                            mimeType: 'text/html',
                            renderVersion: plot.renderVersion,
                        };
                    }

                    return {
                        data: plot.data,
                        mimeType: plot.mimeType,
                        renderVersion: plot.renderVersion,
                    };
                }

                // Return empty if plot not found
                return {
                    data: '',
                    mimeType: 'image/png',
                    renderVersion: 0,
                };
            } finally {
                const claimed = this._renderRequestConnection.get(params.plotId);
                if (claimed === connection) {
                    this._renderRequestConnection.delete(params.plotId);
                }
            }
        });

        // Handle get plots list request.
        // Supports newest-anchor pagination for lazy-loading history:
        // - cursor: number of newest plots already loaded
        // - limit: page size to fetch
        connection.onRequest('plots/list', async (params?: { cursor?: number; limit?: number }) => {
            const ordered = Array.from(this._plots.values());
            const totalCount = ordered.length;

            const rawCursor = typeof params?.cursor === 'number' && Number.isFinite(params.cursor)
                ? params.cursor
                : 0;
            const cursor = Math.min(
                Math.max(0, Math.floor(rawCursor)),
                totalCount,
            );
            const requestedLimit = typeof params?.limit === 'number' && Number.isFinite(params.limit)
                ? params.limit
                : undefined;
            const limit = requestedLimit === undefined
                ? totalCount
                : Math.min(
                    totalCount,
                    Math.max(1, Math.floor(requestedLimit)),
                );

            const endExclusive = Math.max(0, totalCount - cursor);
            const startInclusive = Math.max(0, endExclusive - limit);
            const page = ordered.slice(startInclusive, endExclusive);

            const plots = page.map((plot) => this._serializePlot(plot));

            return {
                plots,
                selectedPlotId: this._getStateForConnection(connection).selectedPlotId,
                totalCount,
                nextCursor: cursor + plots.length,
                hasMore: startInclusive > 0,
            };
        });

        connection.onRequest(PlotsProtocol.SelectPlotZoomRequest.type, async (params) => {
            const plotClient = this._plotsService.positronPlotInstances.find(
                plot => plot.id === params.plotId,
            );
            if (!plotClient || !isZoomablePlotClient(plotClient)) {
                return;
            }

            plotClient.zoomLevel = params.zoomLevel as ZoomLevel;

            const stored = this._plots.get(params.plotId);
            if (stored) {
                stored.zoomLevel = params.zoomLevel;
                this._plots.set(params.plotId, stored);
            }

            if (!(plotClient instanceof PlotClientInstance)) {
                this._notifyConnections(
                    PlotsProtocol.PlotZoomChangedNotification.type,
                    { plotId: params.plotId, zoomLevel: params.zoomLevel },
                );
            }
        });

        // Handle delete plot request
        connection.onRequest('plots/delete', async (params: { plotId: string }) => {
            this._plotsService.removePlot(params.plotId);
            this.log(`Deleted plot ${params.plotId}`, vscode.LogLevel.Debug);
        });

        // Handle clear all plots request
        connection.onRequest('plots/clear', async () => {
            this._plotsService.removeAllPlots();
            this.log('Cleared all plots', vscode.LogLevel.Debug);
        });

        // Handle save plot request
        connection.onRequest('plots/save', async (params: { plotId: string }) => {
            const plot = this._plots.get(params.plotId);
            if (!plot) {
                this.log(`Plot ${params.plotId} not found for save`, vscode.LogLevel.Warning);
                return { success: false, error: 'Plot not found' };
            }
            if (plot.kind === 'html') {
                vscode.window.showWarningMessage('Saving HTML plots is not supported yet.');
                return { success: false, error: 'HTML plot save not supported' };
            }

            try {
                // Show save dialog
                const uri = await vscode.window.showSaveDialog({
                    defaultUri: vscode.Uri.file(`plot-${params.plotId}.png`),
                    filters: {
                        'PNG Image': ['png'],
                        'All Files': ['*']
                    }
                });

                if (uri) {
                    // Convert base64 to buffer and write
                    const base64Data = plot.data.replace(/^data:image\/\w+;base64,/, '');
                    const buffer = Buffer.from(base64Data, 'base64');
                    await vscode.workspace.fs.writeFile(uri, buffer);
                    this.log(`Saved plot ${params.plotId} to ${uri.fsPath}`, vscode.LogLevel.Debug);
                    vscode.window.showInformationMessage(`Plot saved to ${uri.fsPath}`);
                    return { success: true };
                }

                return { success: false, error: 'Save cancelled' };
            } catch (e) {
                this.log(`Failed to save plot: ${e}`, vscode.LogLevel.Warning);
                return { success: false, error: String(e) };
            }
        });

        // Handle copy plot to clipboard request
        connection.onRequest('plots/copy', async (params: { plotId: string }) => {
            const plot = this._plots.get(params.plotId);
            if (!plot) {
                this.log(`Plot ${params.plotId} not found for copy`, vscode.LogLevel.Warning);
                return { success: false, error: 'Plot not found' };
            }
            if (plot.kind === 'html') {
                vscode.window.showWarningMessage('Copying HTML plots is not supported yet.');
                return { success: false, error: 'HTML plot copy not supported' };
            }

            try {
                // Write plot data URI to clipboard as text
                // Note: VS Code clipboard API supports text, for image copy we use the data URI
                await vscode.env.clipboard.writeText(plot.data);
                this.log(`Copied plot ${params.plotId} to clipboard (data URI)`, vscode.LogLevel.Debug);
                vscode.window.showInformationMessage('Plot copied to clipboard');
                return { success: true };
            } catch (e) {
                this.log(`Failed to copy plot: ${e}`, vscode.LogLevel.Warning);
                return { success: false, error: String(e) };
            }
        });

        // ============================================================
        // Sizing Policy RPC Handlers (Positron integration)
        // ============================================================

        // Handle get sizing policies request
        connection.onRequest(PlotsProtocol.GetSizingPoliciesRequest.type, async () => {
            const state = this._getStateForConnection(connection);
            const sourcePolicies = this._plotsService.sizingPolicies;
            const selectedPolicy = this._getSizingPolicyForConnection(state);
            const selectedPlot = this._getSelectedPlotForConnection(state);
            const policies = sourcePolicies.map(p => ({
                id: p.id,
                name: p.getName(selectedPlot as any)
            }));
            return {
                policies,
                selectedPolicyId: selectedPolicy.id
            };
        });

        // Handle select sizing policy request
        connection.onRequest(PlotsProtocol.SelectSizingPolicyRequest.type, async (params) => {
            const state = this._getStateForConnection(connection);
            const selectedPlot = state.selectedPlotId
                ? this._plotsService.positronPlotInstances.find(plot => plot.id === state.selectedPlotId)
                : undefined;

            if (!(selectedPlot instanceof PlotClientInstance)) {
                return;
            }

            if (state.isPrimaryConnection) {
                this._plotsService.selectSizingPolicy(params.policyId);
                this._sendPlotsRenderSettings(state);
                return;
            }

            state.followsServiceSizing = false;
            state.selectedSizingPolicyId = params.policyId;
            state.customSize = undefined;
            state.lastRenderSettingsKey = undefined;

            this._storeSizingForPlotId(state.selectedPlotId, params.policyId, undefined);

            if (state.followsServiceSelection && state.selectedPlotId) {
                this._plotsService.selectPlot(state.selectedPlotId);
                this._plotsService.selectSizingPolicy(params.policyId);
                this._refreshConnectionSizingStateFromSelectedPlot(state);
            }

            this._notifySelectedSizingChanged(state);

            this._sendPlotsRenderSettings(state);
        });
        // Handle set custom size request
        connection.onRequest(PlotsProtocol.SetCustomSizeRequest.type, async (params) => {
            const state = this._getStateForConnection(connection);
            const selectedPlot = state.selectedPlotId
                ? this._plotsService.positronPlotInstances.find(plot => plot.id === state.selectedPlotId)
                : undefined;

            if (!(selectedPlot instanceof PlotClientInstance)) {
                return;
            }

            if (state.isPrimaryConnection) {
                this._plotsService.setCustomPlotSize({
                    width: params.width,
                    height: params.height
                });
                this._sendPlotsRenderSettings(state);
                return;
            }

            state.followsServiceSizing = false;
            state.selectedSizingPolicyId = 'custom';
            state.customSize = {
                width: params.width,
                height: params.height
            };
            state.lastRenderSettingsKey = undefined;

            this._storeSizingForPlotId(state.selectedPlotId, 'custom', state.customSize);

            if (state.followsServiceSelection && state.selectedPlotId) {
                this._plotsService.selectPlot(state.selectedPlotId);
                this._plotsService.setCustomPlotSize({
                    width: params.width,
                    height: params.height
                });
                this._refreshConnectionSizingStateFromSelectedPlot(state);
            }

            this._notifySelectedSizingChanged(state);

            this._sendPlotsRenderSettings(state);
        });
        // Handle clear custom size request
        connection.onRequest(PlotsProtocol.ClearCustomSizeRequest.type, async () => {
            const state = this._getStateForConnection(connection);
            const selectedPlot = state.selectedPlotId
                ? this._plotsService.positronPlotInstances.find(plot => plot.id === state.selectedPlotId)
                : undefined;

            if (!(selectedPlot instanceof PlotClientInstance)) {
                return;
            }

            if (state.isPrimaryConnection) {
                this._plotsService.clearCustomPlotSize();
                this._sendPlotsRenderSettings(state);
                return;
            }

            state.lastRenderSettingsKey = undefined;

            if (state.selectedSizingPolicyId === 'custom') {
                state.selectedSizingPolicyId = 'auto';
                state.customSize = undefined;
            }

            this._storeSizingForPlotId(state.selectedPlotId, state.selectedSizingPolicyId, state.customSize);

            if (state.followsServiceSelection && state.selectedPlotId) {
                this._plotsService.selectPlot(state.selectedPlotId);
                this._plotsService.clearCustomPlotSize();
                this._refreshConnectionSizingStateFromSelectedPlot(state);
            }

            this._notifySelectedSizingChanged(state);

            this._sendPlotsRenderSettings(state);
        });
        // Handle plot selection request
        connection.onRequest(PlotsProtocol.SelectPlotRequest.type, async (params) => {
            const state = this._getStateForConnection(connection);

            if (state.isPrimaryConnection) {
                this._plotsService.selectPlot(params.plotId);
                this._sendPlotsRenderSettings(state);
                return;
            }

            const wasFollowingServiceSelection = state.followsServiceSelection;
            state.selectedPlotId = params.plotId;
            state.followsServiceSelection = false;
            state.followsServiceSizing = false;
            state.lastRenderSettingsKey = undefined;

            const sizingState = this._getSizingStateForPlotId(params.plotId);
            state.selectedSizingPolicyId = sizingState.policyId;
            state.customSize = this._cloneSize(sizingState.customSize);

            this._notifyConnections(
                PlotsProtocol.SelectedPlotChangedNotification.type,
                this._createSelectedPlotChangedPayloadForState(state),
                candidate => candidate === state,
            );
            this._notifySelectedSizingChanged(state);

            this._sendPlotsRenderSettings(state);

            if (wasFollowingServiceSelection) {
                this._plotsService.selectPlot(params.plotId);
            }
        });
        // Handle select history policy request
        connection.onRequest(PlotsProtocol.SelectHistoryPolicyRequest.type, async (params) => {
            this._plotsService.selectHistoryPolicy(params.policy as HistoryPolicy);
        });

        // Handle select history position request
        connection.onRequest(PlotsProtocol.SelectHistoryPositionRequest.type, async (params) => {
            this._plotsService.selectHistoryPosition(params.position as HistoryPosition);
        });

        // Handle get intrinsic size request
        connection.onRequest(PlotsProtocol.GetIntrinsicSizeRequest.type, async (params) => {
            const plotClient = this._plotClients.get(params.plotId);
            if (plotClient) {
                try {
                    const intrinsicSize = await plotClient.getIntrinsicSize();
                    return { intrinsicSize };
                } catch (e) {
                    this.log(`Failed to get intrinsic size: ${e}`, vscode.LogLevel.Warning);
                }
            }
            return { intrinsicSize: undefined };
        });

        // Handle get plot state request
        connection.onRequest(PlotsProtocol.GetPlotStateRequest.type, async (params) => {
            const plotClient = this._plotClients.get(params.plotId);
            if (plotClient) {
                return {
                    state: plotClient.state as PlotsProtocol.PlotClientState,
                    renderEstimateMs: plotClient.renderEstimateMs || 0
                };
            }
            return {
                state: PlotsProtocol.PlotClientState.Unrendered,
                renderEstimateMs: 0
            };
        });

        // Handle open in new window request
        connection.onRequest('plots/openInNewWindow', async (params: { plotId?: string }) => {
            // Get plot data from the provider's own storage
            const plotId = params?.plotId;
            if (!plotId) {
                this.log('No plot ID provided to open in new window', vscode.LogLevel.Debug);
                return { success: false, error: 'No plot ID provided' };
            }

            const plot = this._plots.get(plotId);
            if (!plot) {
                this.log(`Plot ${plotId} not found`, vscode.LogLevel.Warning);
                return { success: false, error: 'Plot not found' };
            }
            try {
                if (plot.kind === 'html') {
                    const htmlClient = this._plotsService.positronPlotInstances.find(candidate => candidate.id === plotId);
                    if (htmlClient instanceof HtmlPlotClient) {
                        await htmlClient.openInBrowser();
                    } else if (plot.htmlUri) {
                        await vscode.env.openExternal(vscode.Uri.parse(plot.htmlUri));
                    } else {
                        return { success: false, error: 'HTML plot URI not found' };
                    }

                    this.log(`Opened HTML plot ${plotId} in browser`, vscode.LogLevel.Debug);
                    return { success: true };
                }

                const plotClient = this._plotClients.get(plotId);
                await this._plotsService.openEditor(
                    plotId,
                    vscode.ViewColumn.Active as unknown as number,
                    plotClient?.metadata,
                    true, // moveToNewWindow
                );
                this.log(`Opened plot ${plotId} in new window`, vscode.LogLevel.Debug);
                return { success: true };
            } catch (e) {
                this.log(`Failed to open plot in new window: ${e}`, vscode.LogLevel.Warning);
                return { success: false, error: String(e) };
            }
        });

        // Handle open in editor request
        connection.onRequest('plots/openInEditor', async (params: { plotId?: string; viewColumn?: 'active' | 'beside' }) => {
            const plotId = params?.plotId;
            if (!plotId) {
                this.log('No plot ID provided to open in editor', vscode.LogLevel.Debug);
                return { success: false, error: 'No plot ID provided' };
            }

            const plot = this._plots.get(plotId);
            if (!plot) {
                this.log(`Plot ${plotId} not found`, vscode.LogLevel.Warning);
                return { success: false, error: 'Plot not found' };
            }
            if (plot.kind === 'html') {
                return { success: false, error: 'HTML plot open in editor not supported' };
            }

            try {
                const viewColumn = params?.viewColumn === 'beside'
                    ? vscode.ViewColumn.Beside
                    : vscode.ViewColumn.Active;
                const plotClient = this._plotClients.get(plotId);
                await this._plotsService.openEditor(plotId, viewColumn as unknown as number, plotClient?.metadata);
                this.log(`Opened plot ${plotId} in editor`, vscode.LogLevel.Debug);
                return { success: true };
            } catch (e) {
                this.log(`Failed to open plot in editor: ${e}`, vscode.LogLevel.Warning);
                return { success: false, error: String(e) };
            }
        });

        // Handle open gallery in new window request
        connection.onRequest('plots/openGalleryInNewWindow', async () => {
            try {
                await vscode.commands.executeCommand(CoreCommandIds.openPlotsGallery, { openInNewWindow: true });
                this.log('Opened plots gallery in new window', vscode.LogLevel.Debug);
                return { success: true };
            } catch (e) {
                this.log('Failed to open plots gallery in new window: ' + String(e), vscode.LogLevel.Warning);
                return { success: false, error: String(e) };
            }
        });

        connection.onRequest('plots/closeAuxPanel', async () => {
            const close = this._auxCloseHandlers.get(connection);
            if (!close) {
                return { success: false, error: 'No auxiliary close handler registered' };
            }

            try {
                close();
                return { success: true };
            } catch (e) {
                return { success: false, error: String(e) };
            }
        });

        connection.onRequest('plots/revealInConsole', async (params: { sessionId: string; executionId?: string }) => {
            try {
                this._consoleService.setActivePositronConsoleSession(params.sessionId);
                if (params.executionId) {
                    this._consoleService.revealExecution(params.sessionId, params.executionId);
                }
                return { success: true };
            } catch (e) {
                this.log('Failed to reveal plot code in console: ' + String(e), vscode.LogLevel.Warning);
                return { success: false, error: String(e) };
            }
        });

        connection.onRequest('plots/activateConsoleSession', async (params: { sessionId: string }) => {
            try {
                this._consoleService.setActivePositronConsoleSession(params.sessionId);
                return { success: true };
            } catch (e) {
                this.log('Failed to activate console session from plot: ' + String(e), vscode.LogLevel.Warning);
                return { success: false, error: String(e) };
            }
        });

        connection.onRequest('plots/openOriginFile', async (params: { plotId: string }) => {
            const plot = this._plots.get(params.plotId);
            if (!plot?.originUri) {
                return { success: false, error: 'Plot origin file not found' };
            }

            try {
                const uri = vscode.Uri.parse(plot.originUri);
                const selection = plot.originRange
                    ? new vscode.Range(
                        plot.originRange.startLine,
                        plot.originRange.startCharacter,
                        plot.originRange.endLine,
                        plot.originRange.endCharacter,
                    )
                    : undefined;

                if (selection) {
                    const document = await vscode.workspace.openTextDocument(uri);
                    await vscode.window.showTextDocument(document, {
                        preview: true,
                        selection,
                    });
                } else {
                    await vscode.commands.executeCommand(
                        'vscode.open',
                        uri,
                        { preview: true },
                    );
                }

                return { success: true };
            } catch (e) {
                this.log('Failed to open plot origin file: ' + String(e), vscode.LogLevel.Warning);
                return { success: false, error: String(e) };
            }
        });

        connection.onRequest('plots/openDarkFilterSettings', async () => {
            try {
                await vscode.commands.executeCommand(
                    'workbench.action.openSettings',
                    'plots.darkFilter',
                );
                return { success: true };
            } catch (e) {
                this.log('Failed to open dark filter settings: ' + String(e), vscode.LogLevel.Warning);
                return { success: false, error: String(e) };
            }
        });

        connection.onRequest('plots/runCodeAgain', async (params: { code: string; sessionId: string; languageId: string }) => {
            try {
                await this._consoleService.executeCode(
                    params.languageId,
                    params.sessionId,
                    params.code,
                    { source: 'plot' },
                    true,
                );
                return { success: true };
            } catch (e) {
                this.log('Failed to run plot code again: ' + String(e), vscode.LogLevel.Warning);
                return { success: false, error: String(e) };
            }
        });
    }

    private async _moveActiveEditorToNewWindow(): Promise<void> {
        await new Promise<void>(resolve => {
            if (typeof queueMicrotask === 'function') {
                queueMicrotask(resolve);
            } else {
                setTimeout(resolve, 0);
            }
        });
        await vscode.commands.executeCommand('workbench.action.moveEditorToNewWindow');
    }

    /** Debounce delay for viewport-triggered render settings (ms). */
    private static readonly RENDER_SETTINGS_DEBOUNCE_MS = 300;

    /**
     * Schedules a debounced call to _sendPlotsRenderSettings.
     * During continuous resize, only the final stable size is sent.
     */
    private _scheduleSendRenderSettings(state: PlotsConnectionState): void {
        if (state.renderSettingsTimeout) {
            clearTimeout(state.renderSettingsTimeout);
        }
        state.renderSettingsTimeout = setTimeout(() => {
            state.renderSettingsTimeout = undefined;
            this._sendPlotsRenderSettings(state);
        }, PlotsViewProvider.RENDER_SETTINGS_DEBOUNCE_MS);
    }

    /**
     * Sends plot render settings to the runtime for pre-rendering.
     */
    private _sendPlotsRenderSettings(state: PlotsConnectionState): void {
        if (!state.followsServiceSizing) {
            return;
        }

        if (!state.lastViewport) {
            return;
        }

        let policy = this._getSizingPolicyForConnection(state);
        if (policy instanceof PlotSizingPolicyIntrinsic) {
            policy = new PlotSizingPolicyAuto();
        }

        const viewportSize = {
            width: state.lastViewport.width,
            height: state.lastViewport.height
        };
        const targetSize = policy.getPlotSize(viewportSize) ?? viewportSize;
        const settings: PlotRenderSettings = {
            size: {
                width: Math.floor(targetSize.width),
                height: Math.floor(targetSize.height)
            },
            pixel_ratio: state.lastViewport.pixelRatio,
            format: state.lastViewport.format
        };

        const key = `${settings.size.width}x${settings.size.height}@${settings.pixel_ratio}-${settings.format}`;
        if (key === state.lastRenderSettingsKey) {
            return;
        }
        state.lastRenderSettingsKey = key;

        this._plotsService.setPlotsRenderSettings(settings);
    }

    private _flushPendingPlotsSync(connection: MessageConnection): void {
        if (!this._isConnectionReady(connection)) {
            return;
        }

        this._sendSessionInfoUpdateToConnection(connection);

        connection.sendNotification(PlotsProtocol.HistoryPolicyChangedNotification.type, {
            policy: this._plotsService.historyPolicy
        });
        connection.sendNotification(PlotsProtocol.HistoryPositionChangedNotification.type, {
            position: this._plotsService.historyPosition
        });

        const state = this._getStateForConnection(connection);
        const selectedPolicy = this._getSizingPolicyForConnection(state);

        connection.sendNotification(PlotsProtocol.SizingPolicyChangedNotification.type, {
            plotId: state.selectedPlotId,
            policyId: selectedPolicy.id,
            policyName: selectedPolicy.getName(this._getSelectedPlotForConnection(state) as any),
            policies: this._getSizingPoliciesPayload(state),
            customSize: selectedPolicy instanceof PlotSizingPolicyCustom
                ? this._cloneSize(selectedPolicy.size)
                : undefined,
        });

        connection.sendNotification(
            PlotsProtocol.SelectedPlotChangedNotification.type,
            this._createSelectedPlotChangedPayloadForState(state),
        );
    }

    private _getSizingPoliciesPayload(state: PlotsConnectionState): PlotsProtocol.SizingPolicyInfo[] {
        const selectedPlot = this._getSelectedPlotForConnection(state);
        return this._getSizingPoliciesPayloadForPlot(selectedPlot);
    }

    private _getSizingPoliciesPayloadForPlot(
        selectedPlot: PlotClientInstance | undefined
    ): PlotsProtocol.SizingPolicyInfo[] {
        return this._plotsService.sizingPolicies.map(policy => ({
            id: policy.id,
            name: policy.getName(selectedPlot as any)
        }));
    }

    private _notifySelectedSizingChanged(state: PlotsConnectionState): void {
        const selectedPlot = this._getSelectedPlotForConnection(state);
        const selectedPolicy = this._getSizingPolicyForConnection(state);

        this._notifyConnections(
            PlotsProtocol.SizingPolicyChangedNotification.type,
            {
                plotId: state.selectedPlotId,
                policyId: selectedPolicy.id,
                policyName: selectedPolicy.getName(selectedPlot as any),
                policies: this._getSizingPoliciesPayload(state),
                customSize: selectedPolicy instanceof PlotSizingPolicyCustom
                    ? this._cloneSize(selectedPolicy.size)
                    : undefined,
            },
            candidate => candidate === state,
        );

        this._notifyConnections(
            PlotsProtocol.SelectedPlotChangedNotification.type,
            this._createSelectedPlotChangedPayloadForState(state),
            candidate => candidate === state,
        );
    }


    protected _getHtmlContent(webview: vscode.Webview): string {
        const scriptUri = this._getWebviewUri(webview, 'webview', 'dist', 'plots', 'index.js');
        const styleUri = this._getWebviewUri(webview, 'webview', 'dist', 'plots', 'index.css');
        const nonce = this._getNonce();

        return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src ${webview.cspSource} 'unsafe-inline'; script-src 'nonce-${nonce}'; font-src ${webview.cspSource} data:; img-src ${webview.cspSource} data:; frame-src http: https: ${webview.cspSource};">
    <link href="${styleUri}" rel="stylesheet">
    <title>Plots</title>
</head>
<body>
    <div id="app"></div>
    <script type="module" nonce="${nonce}" src="${scriptUri}"></script>
</body>
</html>`;
    }

    /**
     * Sends a plot added notification to the webview
     */
    sendPlotAdded(plot: PlotData): void {
        if (!plot.sessionId) {
            this.log(`Dropping plot ${plot.id} without sessionId`, vscode.LogLevel.Debug);
            return;
        }

        const serialized = this._serializePlot(plot);

        void this._revealPlotsIfHidden(true);
        this._notifyConnections(
            PlotsProtocol.PlotAddedNotification.type,
            toPlotAddedParams(serialized),
        );
    }

    /**
     * Clears all plots
     */
    clearPlots(): void {
        this._plotsService.removeAllPlots();
    }

    private async _revealPlotsIfHidden(preserveFocus: boolean): Promise<void> {
        const view = this.view;
        if (view) {
            if (!view.visible) {
                view.show(preserveFocus);
            }
            return;
        }

        const editorToRestore = preserveFocus ? vscode.window.activeTextEditor : undefined;
        const restoreFocus = async (): Promise<void> => {
            if (!editorToRestore) {
                return;
            }
            await vscode.window.showTextDocument(editorToRestore.document, {
                viewColumn: editorToRestore.viewColumn,
                preserveFocus: false
            });
        };

        try {
            await vscode.commands.executeCommand('workbench.views.action.showView', ViewIds.plots);
        } catch (err) {
            this.log(`Failed to reveal plots view: ${err}`, vscode.LogLevel.Warning);
            try {
                await vscode.commands.executeCommand(WorkbenchViewContainerCommands.sessionSidebar);
            } catch (fallbackErr) {
                this.log(`Failed to reveal plots container: ${fallbackErr}`, vscode.LogLevel.Warning);
            }
        } finally {
            await restoreFocus();
        }
    }
}
