import * as vscode from 'vscode';

export type WebviewLocalizationMessages = Readonly<Record<string, string>>;

/**
 * Shared localization payload for extension-owned Webviews. Components use
 * stable semantic keys while vscode.l10n remains the single translation
 * authority in the extension host.
 */
export function createWebviewLocalizationMessages(): WebviewLocalizationMessages {
    return {
        'common.cancel': vscode.l10n.t('Cancel'),
        'common.close': vscode.l10n.t('Close'),
        'common.copy': vscode.l10n.t('Copy'),
        'common.loading': vscode.l10n.t('Loading'),
        'common.paste': vscode.l10n.t('Paste'),
        'common.selectAll': vscode.l10n.t('Select All'),
        'common.openInBrowser': vscode.l10n.t('Open in Browser'),
        'common.openInEditorTab': vscode.l10n.t('Open in Editor Tab'),
        'common.openInNewWindow': vscode.l10n.t('Open in New Window'),
        'common.selectWhereToOpen': vscode.l10n.t('Select where to open'),
        'console.hideTraceback': vscode.l10n.t('Hide Traceback'),
        'console.initializing': vscode.l10n.t('Waiting for extensions'),
        'console.awaitingTrust': vscode.l10n.t('Cannot start consoles in Restricted Mode.'),
        'console.trustFolder': vscode.l10n.t('Trust this folder'),
        'console.enableConsoles': vscode.l10n.t('to enable consoles.'),
        'console.actions': vscode.l10n.t('Console actions'),
        'console.noSessions': vscode.l10n.t('No sessions'),
        'console.noSessionRunning': vscode.l10n.t('There is no session running.'),
        'console.use': vscode.l10n.t('Use'),
        'console.startSession': vscode.l10n.t('Start Session'),
        'console.emptyPrefix': vscode.l10n.t('There is no session running. Use'),
        'console.emptySuffix': vscode.l10n.t('to start one.'),
        'console.sessionStarted': vscode.l10n.t('{0} started.'),
        'console.sessionRestarted': vscode.l10n.t('{0} restarted.'),
        'console.extensionsRestarting': vscode.l10n.t('Extensions restarting...'),
        'console.runtimeItemUnknown': vscode.l10n.t('Unknown runtime item type'),
        'console.activityItemUnknown': vscode.l10n.t('Unknown activity item'),
        'console.runtimeFailedToStart': vscode.l10n.t('Runtime failed to start.'),
        'console.newFolderTasks': vscode.l10n.t('Setting up workspace'),
        'console.reconnecting': vscode.l10n.t('Reconnecting'),
        'console.preparing': vscode.l10n.t('Preparing'),
        'console.starting': vscode.l10n.t('Starting'),
        'console.discovering': vscode.l10n.t('Discovering interpreters'),
        'console.interruptExecution': vscode.l10n.t('Interrupt Execution'),
        'console.restartLanguage': vscode.l10n.t('Restart {0}'),
        'console.session': vscode.l10n.t('Session'),
        'console.toggleWordWrap': vscode.l10n.t('Toggle Word Wrap'),
        'console.clearConsole': vscode.l10n.t('Clear Console'),
        'console.toggleTrace': vscode.l10n.t('Toggle Trace'),
        'console.deleteSession': vscode.l10n.t('Delete Session'),
        'console.openInEditor': vscode.l10n.t('Open in Editor'),
        'console.showResourceMonitor': vscode.l10n.t('Show Resource Monitor'),
        'console.rename': vscode.l10n.t('Rename...'),
        'console.find.placeholder': vscode.l10n.t('Find'),
        'console.find.invalidRegex': vscode.l10n.t('Invalid regex'),
        'console.find.noResults': vscode.l10n.t('No results'),
        'console.find.matchCount': vscode.l10n.t('{0} of {1}'),
        'console.find.matchCountLimited': vscode.l10n.t('{0} of 1000+'),
        'console.find.resize': vscode.l10n.t('Resize Find'),
        'console.find.matchCase': vscode.l10n.t('Match Case'),
        'console.find.matchWholeWord': vscode.l10n.t('Match Whole Word'),
        'console.find.useRegex': vscode.l10n.t('Use Regular Expression'),
        'console.find.previous': vscode.l10n.t('Previous Match'),
        'console.find.previousWithKey': vscode.l10n.t('Previous Match (Enter)'),
        'console.find.next': vscode.l10n.t('Next Match'),
        'console.find.nextWithKey': vscode.l10n.t('Next Match (Shift+Enter)'),
        'console.find.closeWithKey': vscode.l10n.t('Close (Escape)'),
        'console.history.noMatches': vscode.l10n.t('No matching history items'),
        'console.history.browser': vscode.l10n.t('History browser'),
        'console.resizeSessionList': vscode.l10n.t('Resize console session list'),
        'console.cwd.label': vscode.l10n.t('Current Working Directory'),
        'console.cwd.doubleClickCopy': vscode.l10n.t('Double-click to copy path'),
        'console.cwd.copied': vscode.l10n.t('Path copied'),
        'console.info.title': vscode.l10n.t('Console Information'),
        'console.info.sessionId': vscode.l10n.t('Session ID: {0}'),
        'console.info.state': vscode.l10n.t('State: {0}'),
        'console.info.runtimePath': vscode.l10n.t('Path: {0}'),
        'console.info.runtimeSource': vscode.l10n.t('Source: {0}'),
        'console.info.showOutputChannel': vscode.l10n.t('Show {0} Output Channel'),
        'console.info.channel.kernel': vscode.l10n.t('Kernel'),
        'console.info.channel.console': vscode.l10n.t('Supervisor'),
        'console.info.channel.lsp': vscode.l10n.t('LSP'),
        'console.state.uninitialized': vscode.l10n.t('Uninitialized'),
        'console.state.ready': vscode.l10n.t('Ready'),
        'console.state.busy': vscode.l10n.t('Busy'),
        'console.state.interrupting': vscode.l10n.t('Interrupting'),
        'console.state.starting': vscode.l10n.t('Starting'),
        'console.state.restarting': vscode.l10n.t('Restarting'),
        'console.state.exiting': vscode.l10n.t('Shutting Down'),
        'console.state.exited': vscode.l10n.t('Exited'),
        'console.state.offline': vscode.l10n.t('Offline'),
        'console.state.disconnected': vscode.l10n.t('Disconnected'),
        'console.resource.aria': vscode.l10n.t('Runtime resource usage: CPU {0}%, memory {1} bytes'),
        'console.resource.unavailable': vscode.l10n.t('Runtime resource usage unavailable'),
        'console.resource.cpu': vscode.l10n.t('CPU'),
        'console.resource.cpuUsage': vscode.l10n.t('CPU usage'),
        'console.resource.memoryShort': vscode.l10n.t('MEM'),
        'console.resource.cpuTooltip': vscode.l10n.t('CPU {0}%'),
        'console.resource.memoryTooltip': vscode.l10n.t('Memory {0}'),
        'console.submittingCode': vscode.l10n.t('Submitting code'),
        'console.plot.select': vscode.l10n.t('Select this plot in the Plots pane'),
        'console.plot.output': vscode.l10n.t('Plot output'),
        'console.showTraceback': vscode.l10n.t('Show Traceback'),
        'console.submitting': vscode.l10n.t('Submitting...'),
        'console.suggestionUnavailable': vscode.l10n.t('Suggestion unavailable after restore'),
        'dataExplorer.actions': vscode.l10n.t('Data Explorer actions'),
        'dataExplorer.ariaLabel': vscode.l10n.t('Data Explorer'),
        'dataExplorer.columnSummary': vscode.l10n.t('Column Summary'),
        'dataExplorer.collapseSummary': vscode.l10n.t('Collapse summary'),
        'dataExplorer.dismiss': vscode.l10n.t('Dismiss'),
        'dataExplorer.dismissError': vscode.l10n.t('Dismiss error'),
        'dataExplorer.expandSummary': vscode.l10n.t('Expand summary'),
        'dataExplorer.largeColumnWarning': vscode.l10n.t('This dataset has too many columns for sorting, filtering, and column summary operations.'),
        'dataExplorer.loading': vscode.l10n.t('Loading Data Explorer'),
        'dataExplorer.openAsSpreadsheet': vscode.l10n.t('Open as Spreadsheet'),
        'dataExplorer.resizeSummary': vscode.l10n.t('Resize summary panel'),
        'positron.addEditRowFilter.applyFilter': vscode.l10n.t('Apply Filter'),
        'positron.addEditRowFilter.conditionIsBetween': vscode.l10n.t('is between'),
        'positron.addEditRowFilter.conditionIsEmpty': vscode.l10n.t('is empty'),
        'positron.addEditRowFilter.conditionIsEqualTo': vscode.l10n.t('is equal to'),
        'positron.addEditRowFilter.conditionIsFalse': vscode.l10n.t('is false'),
        'positron.addEditRowFilter.conditionIsGreaterThan': vscode.l10n.t('is greater than'),
        'positron.addEditRowFilter.conditionIsGreaterThanOrEqual': vscode.l10n.t('is greater than or equal to'),
        'positron.addEditRowFilter.conditionIsLessThan': vscode.l10n.t('is less than'),
        'positron.addEditRowFilter.conditionIsLessThanOrEqual': vscode.l10n.t('is less than or equal to'),
        'positron.addEditRowFilter.conditionIsNotBetween': vscode.l10n.t('is not between'),
        'positron.addEditRowFilter.conditionIsNotEmpty': vscode.l10n.t('is not empty'),
        'positron.addEditRowFilter.conditionIsNotEqualTo': vscode.l10n.t('is not equal to'),
        'positron.addEditRowFilter.conditionIsNotNull': vscode.l10n.t('is not missing'),
        'positron.addEditRowFilter.conditionIsNull': vscode.l10n.t('is missing'),
        'positron.addEditRowFilter.conditionIsTrue': vscode.l10n.t('is true'),
        'positron.addEditRowFilter.conditionSearchContains': vscode.l10n.t('contains'),
        'positron.addEditRowFilter.conditionSearchEndsWith': vscode.l10n.t('ends with'),
        'positron.addEditRowFilter.conditionSearchNotContains': vscode.l10n.t('does not contain'),
        'positron.addEditRowFilter.conditionSearchRegexMatches': vscode.l10n.t('regex matches'),
        'positron.addEditRowFilter.conditionSearchStartsWith': vscode.l10n.t('starts with'),
        'positron.addEditRowFilter.lowerLimitPlaceholder': vscode.l10n.t('lower limit'),
        'positron.addEditRowFilter.pleaseSelectColumn': vscode.l10n.t('Please select the column.'),
        'positron.addEditRowFilter.pleaseSelectCondition': vscode.l10n.t('Please select the condition.'),
        'positron.addEditRowFilter.pleaseSupplyLowerLimit': vscode.l10n.t('Please supply the lower limit.'),
        'positron.addEditRowFilter.pleaseSupplyUpperLimit': vscode.l10n.t('Please supply the upper limit.'),
        'positron.addEditRowFilter.pleaseSupplyValidLowerLimit': vscode.l10n.t('Please supply a valid lower limit.'),
        'positron.addEditRowFilter.pleaseSupplyValidUpperLimit': vscode.l10n.t('Please supply a valid upper limit.'),
        'positron.addEditRowFilter.pleaseSupplyValidValue': vscode.l10n.t('Please supply a valid value.'),
        'positron.addEditRowFilter.pleaseSupplyValue': vscode.l10n.t('Please supply the value.'),
        'positron.addEditRowFilter.selectColumn': vscode.l10n.t('Select Column'),
        'positron.addEditRowFilter.selectCondition': vscode.l10n.t('Select Condition'),
        'positron.addEditRowFilter.upperLimitPlaceholder': vscode.l10n.t('upper limit'),
        'positron.addEditRowFilter.valuePlaceholder': vscode.l10n.t('value'),
        'positron.addFilter': vscode.l10n.t('Add Filter'),
        'positron.and': vscode.l10n.t('and'),
        'positron.clearFilter': vscode.l10n.t('Clear Filter'),
        'positron.clearFilters': vscode.l10n.t('Clear Filters'),
        'positron.clearSearch': vscode.l10n.t('Clear search'),
        'positron.clearSorting': vscode.l10n.t('Clear Sorting'),
        'positron.columnSummary.collapse': vscode.l10n.t('Collapse'),
        'positron.columnSummary.expand': vscode.l10n.t('Expand'),
        'positron.dataExplorer.codeSyntaxHeading': vscode.l10n.t('Select code syntax'),
        'positron.dataExplorer.computing': vscode.l10n.t('Computing'),
        'positron.dataExplorer.convertToCode.empty': vscode.l10n.t('No preview is available for the current selection.'),
        'positron.dataExplorer.convertToCode.loading': vscode.l10n.t('Generating preview...'),
        'positron.dataExplorer.copy': vscode.l10n.t('Copy'),
        'positron.dataExplorer.copyColumn': vscode.l10n.t('Copy Column'),
        'positron.dataExplorer.copyRow': vscode.l10n.t('Copy Row'),
        'positron.dataExplorer.disconnected': vscode.l10n.t('Disconnected'),
        'positron.dataExplorer.error': vscode.l10n.t('Error'),
        'positron.dataExplorer.filtering.filterLimit': vscode.l10n.t('The maximum number of filters has been reached.'),
        'positron.dataExplorer.idle': vscode.l10n.t('Idle'),
        'positron.dataExplorer.pinColumn': vscode.l10n.t('Pin Column'),
        'positron.dataExplorer.pinRow': vscode.l10n.t('Pin Row'),
        'positron.dataExplorer.positronCopyCode': vscode.l10n.t('Copy Code'),
        'positron.dataExplorer.selectCodeSyntax': vscode.l10n.t('Select Code Syntax'),
        'positron.dataExplorer.selectColumn': vscode.l10n.t('Select Column'),
        'positron.dataExplorer.selectRow': vscode.l10n.t('Select Row'),
        'positron.dataExplorer.sort': vscode.l10n.t('Sort summary row data'),
        'positron.dataExplorer.sortByNameAsc': vscode.l10n.t('Sort by Name, Ascending'),
        'positron.dataExplorer.sortByNameDesc': vscode.l10n.t('Sort by Name, Descending'),
        'positron.dataExplorer.sortByOriginal': vscode.l10n.t('Sort by Original'),
        'positron.dataExplorer.sortByTypeAsc': vscode.l10n.t('Sort by Type, Ascending'),
        'positron.dataExplorer.sortByTypeDesc': vscode.l10n.t('Sort by Type, Descending'),
        'positron.dataExplorer.unpinColumn': vscode.l10n.t('Unpin Column'),
        'positron.dataExplorer.unpinRow': vscode.l10n.t('Unpin Row'),
        'positron.editFilter': vscode.l10n.t('Edit Filter'),
        'positron.fileOptions.apply': vscode.l10n.t('Apply'),
        'positron.fileOptions.hasHeaderRow': vscode.l10n.t('First row contains column names'),
        'positron.fileOptions.worksheet': vscode.l10n.t('Worksheet'),
        'positron.fileOptionsModalDialogTitle': vscode.l10n.t('File Options'),
        'positron.hideFilters': vscode.l10n.t('Hide Filters'),
        'positron.isEmpty': vscode.l10n.t('is empty'),
        'positron.isFalse': vscode.l10n.t('is false'),
        'positron.isMissing': vscode.l10n.t('is missing'),
        'positron.isNotEmpty': vscode.l10n.t('is not empty'),
        'positron.isNotMissing': vscode.l10n.t('is not missing'),
        'positron.isTrue': vscode.l10n.t('is true'),
        'positron.manageFilters': vscode.l10n.t('Manage Filters'),
        'positron.missingValues.all': vscode.l10n.t('All values are missing ({0} values)'),
        'positron.missingValues.calculating': vscode.l10n.t('Calculating...'),
        'positron.missingValues.none': vscode.l10n.t('No missing values'),
        'positron.missingValues.some': vscode.l10n.t('{0} of values are missing ({1} values)'),
        'positron.sayHello': vscode.l10n.t('hello {0}'),
        'positron.searchPlacehold': vscode.l10n.t('search'),
        'positron.showFilters': vscode.l10n.t('Show Filters'),
        'positron.sortAscending': vscode.l10n.t('Sort Ascending'),
        'positron.sortDescending': vscode.l10n.t('Sort Descending'),
        'positron.statusBar.columns': vscode.l10n.t('columns'),
        'positron.statusBar.rows': vscode.l10n.t('rows'),
        'positron.statusBar.showing': vscode.l10n.t('Showing'),
        'positron.statusBar.total': vscode.l10n.t('total'),
        'positron.unknown': vscode.l10n.t('Unknown'),
        'positronCancel': vscode.l10n.t('Cancel'),
        'positronConvertToCodeModalDialogTitle': vscode.l10n.t('Convert to Code'),
        'positronEmpty': vscode.l10n.t('Empty'),
        'positronFalse': vscode.l10n.t('False'),
        'positronMax': vscode.l10n.t('Max'),
        'positronMean': vscode.l10n.t('Mean'),
        'positronMedian': vscode.l10n.t('Median'),
        'positronMin': vscode.l10n.t('Min'),
        'positronMissing': vscode.l10n.t('Missing'),
        'positronNA': vscode.l10n.t('N/A'),
        'positronOK': vscode.l10n.t('OK'),
        'positronSD': vscode.l10n.t('SD'),
        'positronTimezone': vscode.l10n.t('Timezone'),
        'positronTrue': vscode.l10n.t('True'),
        'positronUnique': vscode.l10n.t('Unique'),
        'memory.computing': vscode.l10n.t('Computing memory usage...'),
        'memory.extensionHostAndKernels': vscode.l10n.t('Extension Host + kernels'),
        'memory.free': vscode.l10n.t('Free'),
        'memory.memoryUsage': vscode.l10n.t('Memory usage'),
        'memory.other': vscode.l10n.t('Other'),
        'memory.overhead': vscode.l10n.t('Overhead'),
        'memory.platform': vscode.l10n.t('Platform'),
        'memory.sessions': vscode.l10n.t('Sessions'),
        'memory.summary': vscode.l10n.t('Summary'),
        'memory.used': vscode.l10n.t('{0} used'),
        'memory.configure': vscode.l10n.t('Configure'),
        'memory.extensionHost': vscode.l10n.t('Extension Host'),
        'memory.mem': vscode.l10n.t('Mem'),
        'memory.lessThanPercentRemaining': vscode.l10n.t('Less than {0}% memory remaining', '{0}'),
        'memory.lessThanMegabytesRemaining': vscode.l10n.t('Less than {0} MB memory remaining', '{0}'),
        'variables.refreshObjects': vscode.l10n.t('Refresh Objects'),
        'variables.deleteAllObjects': vscode.l10n.t('Delete All Objects'),
        'variables.noVariables': vscode.l10n.t('No variables have been created.'),
        'variables.noMatches': vscode.l10n.t('No variables match the current filter.'),
        'variables.grouping': vscode.l10n.t('Change how variables are grouped'),
        'variables.sorting': vscode.l10n.t('Change how variables are sorted'),
        'variables.highlightRecent': vscode.l10n.t('Highlight recent values'),
        'variables.noActiveSession': vscode.l10n.t('There is no active session.'),
        'variables.filter': vscode.l10n.t('Filter'),
        'variables.none': vscode.l10n.t('None'),
        'variables.kind': vscode.l10n.t('Kind'),
        'variables.size': vscode.l10n.t('Size'),
        'variables.name': vscode.l10n.t('Name'),
        'variables.recent': vscode.l10n.t('Recent'),
        'variables.expand': vscode.l10n.t('Expand'),
        'variables.collapse': vscode.l10n.t('Collapse'),
        'variables.copyName': vscode.l10n.t('Copy Name'),
        'variables.copyValue': vscode.l10n.t('Copy Value'),
        'variables.copyAsText': vscode.l10n.t('Copy as Text'),
        'variables.copyAsHtml': vscode.l10n.t('Copy as HTML'),
        'variables.view': vscode.l10n.t('View'),
        'variables.viewDataTable': vscode.l10n.t('View Data Table'),
        'variables.viewConnection': vscode.l10n.t('View Connection'),
        'variables.loading': vscode.l10n.t('Loading...'),
        'variables.moreValues': vscode.l10n.t('{0} more values', '{0}'),
        'variables.deleteAllTitle': vscode.l10n.t('Delete All Variables'),
        'variables.deleteAllMessage': vscode.l10n.t('Are you sure you want to delete all variables? This operation cannot be undone.'),
        'variables.delete': vscode.l10n.t('Delete'),
        'plots.copyPlot': vscode.l10n.t('Copy plot to clipboard'),
        'plots.clearAll': vscode.l10n.t('Clear all plots'),
        'plots.next': vscode.l10n.t('Show next plot'),
        'plots.openEditorTab': vscode.l10n.t('Open in editor tab'),
        'plots.openNewWindow': vscode.l10n.t('Open in new window'),
        'plots.previous': vscode.l10n.t('Show previous plot'),
        'plots.save': vscode.l10n.t('Save plot'),
        'plots.openInEditor': vscode.l10n.t('Open in editor'),
        'plots.openInEditorSide': vscode.l10n.t('Open in editor tab to the Side'),
        'plots.selectWhereToOpen': vscode.l10n.t('Select where to open plot'),
        'viewer.actions': vscode.l10n.t('Viewer actions'),
        'viewer.clearContent': vscode.l10n.t('Clear the content'),
        'viewer.clearUrl': vscode.l10n.t('Clear the current URL'),
        'viewer.currentUrl': vscode.l10n.t('The current URL'),
        'viewer.interrupt': vscode.l10n.t('Interrupt execution'),
        'viewer.loading': vscode.l10n.t('Loading preview'),
        'viewer.navigateBack': vscode.l10n.t('Navigate back to the previous URL'),
        'viewer.navigateForward': vscode.l10n.t('Navigate forward to the next URL'),
        'viewer.navigateUrl': vscode.l10n.t('Navigate to URL'),
        'viewer.noPreview': vscode.l10n.t('No preview to display'),
        'viewer.noPreviewHint': vscode.l10n.t('Run code that produces HTML output to see it here'),
        'viewer.reloadContent': vscode.l10n.t('Reload the content'),
        'viewer.reloadUrl': vscode.l10n.t('Reload the current URL'),
        'viewer.tryAgain': vscode.l10n.t('Try Again'),
        'viewer.unableToLoad': vscode.l10n.t('Unable to load preview'),
        'viewer.unavailableHint': vscode.l10n.t('The content may no longer be available.'),
    };
}

export function serializeWebviewLocalizationMessages(): string {
    return JSON.stringify(createWebviewLocalizationMessages()).replace(/</g, '\\u003c');
}
