/*---------------------------------------------------------------------------------------------
 *  Copyright (C) 2024-2025 Posit Software, PBC. All rights reserved.
 *  Licensed under the Elastic License 2.0. See LICENSE.txt for license information.
 *--------------------------------------------------------------------------------------------*/

import * as vscode from 'vscode';
import { PlotMetadata } from './PlotClientInstance';
import { IPositronPlotClient } from './positronPlots';

/**
 * Event data for showing an HTML URI.
 */
export interface IShowHtmlUriEvent {
    /** The URI of the HTML content */
    uri: vscode.Uri;
    /** Whether to show in an external browser */
    isExternal?: boolean;
    /** The title for the preview */
    title?: string;
}

/**
 * A Positron plot instance that contains content from an HTML file.
 *
 * Matches Positron's HtmlPlotClient implementation.
 *
 * This client manages HTML content that can be displayed in a webview,
 * such as interactive plots generated by htmlwidgets or similar libraries.
 */
export class HtmlPlotClient implements IPositronPlotClient, vscode.Disposable {
    /** The plot metadata */
    public readonly metadata: PlotMetadata;

    /** The HTML content URI */
    private readonly _uri: vscode.Uri;

    /** Event emitter for metadata updates */
    private readonly _onDidUpdateMetadata = new vscode.EventEmitter<PlotMetadata>();

    /** Disposables */
    private readonly _disposables: vscode.Disposable[] = [];

    /** Claimants currently holding this HTML client */
    private readonly _claimants = new Set<unknown>();

    /** Last known layout from the claimant viewport */
    private _lastLayout: { width: number; height: number } | undefined;

    /** Static counter for generating unique IDs */
    private static _nextId = 0;

    /**
     * Creates an HtmlPlotClient from persisted metadata.
     */
    static fromMetadata(metadata: PlotMetadata, uri: vscode.Uri): HtmlPlotClient {
        const client = new HtmlPlotClient(
            metadata.session_id,
            { uri, title: metadata.name },
            metadata.execution_id,
            metadata.code
        );

        // Overwrite metadata with persisted values
        client.metadata.id = metadata.id;
        client.metadata.created = metadata.created ?? Date.now();
        client.metadata.kind = metadata.kind ?? 'html';
        client.metadata.name = metadata.name;
        client.metadata.execution_id = metadata.execution_id;
        client.metadata.code = metadata.code ?? '';
        client.metadata.session_id = metadata.session_id;
        client.metadata.output_id = metadata.output_id;
        client.metadata.suggested_file_name = metadata.suggested_file_name;
        client.metadata.zoom_level = metadata.zoom_level;
        client.metadata.sizing_policy = metadata.sizing_policy;
        client.metadata.location = metadata.location;
        client.metadata.pre_render = metadata.pre_render;
        client.metadata.html_uri = metadata.html_uri;
        client.metadata.language = metadata.language;

        return client;
    }

    /** Whether the webview is currently active */
    private _isActive = false;

    /**
     * Creates a new HtmlPlotClient.
     *
     * @param sessionId The session ID that created this plot
     * @param event The event containing the HTML URI
     * @param executionId The execution ID (optional)
     * @param code The code that generated this HTML (optional)
     */
    constructor(
        sessionId: string,
        event: IShowHtmlUriEvent,
        executionId?: string,
        code?: string
    ) {
        this._uri = event.uri;

        // Create the metadata
        this.metadata = {
            id: `html-plot-${HtmlPlotClient._nextId++}`,
            created: Date.now(),
            session_id: sessionId,
            execution_id: executionId,
            code: code ?? '',
            name: event.title || `Interactive Plot ${HtmlPlotClient._nextId}`,
            kind: 'html',
            html_uri: event.uri.toString()
        };

        this._disposables.push(this._onDidUpdateMetadata);
    }

    /** Gets the unique ID of the plot */
    get id(): string {
        return this.metadata.id;
    }

    /** Gets the HTML URI */
    get uri(): vscode.Uri {
        return this._uri;
    }

    /** Event that fires when the metadata is updated */
    get onDidUpdateMetadata(): vscode.Event<PlotMetadata> {
        return this._onDidUpdateMetadata.event;
    }

    /**
     * Last known claimed layout dimensions.
     */
    get lastLayout(): { width: number; height: number } | undefined {
        return this._lastLayout;
    }

    /**
     * Deactivates the plot lifecycle.
     */
    deactivate(): void {
        this._isActive = false;
    }

    /**
     * Claims the HTML plot lifecycle for a particular host.
     */
    claim(claimant: unknown): void {
        if (claimant === undefined || claimant === null) {
            return;
        }

        this._claimants.add(claimant);
        if (!this._isActive) {
            this._isActive = true;
        }
    }

    /**
     * Releases a previous claim on the HTML plot lifecycle.
     */
    release(claimant: unknown): void {
        if (claimant !== undefined && claimant !== null) {
            this._claimants.delete(claimant);
        }

        if (this._claimants.size === 0) {
            this.deactivate();
        }
    }

    /**
     * Updates the claimed layout dimensions.
     */
    layout(width: number, height: number): void {
        if (width <= 0 || height <= 0) {
            return;
        }

        this._lastLayout = { width, height };
    }

    /**
     * Opens the HTML content in an external browser.
     */
    async openInBrowser(): Promise<void> {
        await vscode.env.openExternal(this._uri);
    }

    /**
     * Disposes the HTML plot client.
     */
    dispose(): void {
        this._claimants.clear();
        this.deactivate();
        this._disposables.forEach(d => d.dispose());
    }
}
