/*---------------------------------------------------------------------------------------------
 *  AUTO-GENERATED from contracts/console.json. Do not edit this file directly.
 *--------------------------------------------------------------------------------------------*/

import { NotificationType, RequestType, RequestType0 } from 'vscode-jsonrpc';

export interface CompletionItem {
    label: string;
    kind?: string;
    detail?: string;
    documentation?: string;
    insertText?: string;
}

export interface RuntimeResourceUsage {
    cpu_percent: number;
    memory_bytes: number;
    thread_count?: number;
    sampling_period_ms?: number;
    timestamp?: number;
}

export interface ConsoleThemeRule {
    token: string;
    foreground?: string;
    background?: string;
    fontStyle?: string;
}

export interface ConsoleThemeData {
    base: 'vs' | 'vs-dark' | 'hc-black' | 'hc-light';
    rules: ConsoleThemeRule[];
}

export interface ConsoleSettings {
    scrollbackSize: number;
    fontFamily: string;
    fontSize: number;
    lineHeight: number;
}

export interface SerializedRuntimeItemPayload {
    type: string;
}

export interface SerializedActivityItemPayload {
    type: string;
}

export interface ConsoleRuntimeChange {
    kind: 'appendRuntimeItem' | 'appendActivityItem' | 'replaceActivityOutput' | 'clearActivityOutput' | 'updateActivityInputState';
    parentId?: string;
    outputId?: string;
    state?: 'provisional' | 'executing' | 'completed' | 'cancelled';
    runtimeItem?: SerializedRuntimeItemPayload;
    activityItem?: SerializedActivityItemPayload;
}

export namespace ExecuteRequest {

    export interface Params {
        code: string;
        executionId?: string;
        allowIncomplete?: boolean;
        mode?: 'interactive' | 'non-interactive' | 'silent' | 'transient';
        errorBehavior?: 'continue' | 'stop';
        sessionId?: string;
    }

    export interface Result {
        executionId: string;
    }

    export const type = new RequestType<Params, Result, void>('console/execute');
}

export namespace CompleteRequest {

    export interface Params {
        code: string;
        cursorPos: number;
        sessionId?: string;
    }

    export interface Result {
        items: CompletionItem[];
    }

    export const type = new RequestType<Params, Result, void>('console/complete');
}

export namespace IsCompleteRequest {

    export interface Params {
        code: string;
        sessionId?: string;
    }

    export interface Result {
        status: 'complete' | 'incomplete' | 'invalid' | 'unknown';
    }

    export const type = new RequestType<Params, Result, void>('console/isComplete');
}

export namespace InterruptRequest {

    export interface Params {
        sessionId?: string;
    }

    export const type = new RequestType<Params | void, void, void>('console/interrupt');
}

export namespace ClearConsoleRequest {

    export interface Params {
        sessionId?: string;
    }

    export const type = new RequestType<Params | void, void, void>('console/clearConsole');
}

export namespace ToggleWordWrapRequest {

    export interface Params {
        sessionId?: string;
    }

    export const type = new RequestType<Params | void, void, void>('console/toggleWordWrap');
}

export namespace ToggleTraceRequest {

    export interface Params {
        sessionId?: string;
    }

    export const type = new RequestType<Params | void, void, void>('console/toggleTrace');
}

export namespace GetHistoryRequest {

    export interface Result {
        entries: string[];
    }

    export const type = new RequestType0<Result, void>('console/getHistory');
}

export namespace AddHistoryRequest {

    export interface Params {
        code: string;
    }

    export const type = new RequestType<Params, void, void>('console/addHistory');
}

export namespace GetConsoleSettingsRequest {

    export const type = new RequestType0<ConsoleSettings, void>('console/getSettings');
}

export namespace ConsoleRequestFullStateRequest {

    export interface Params {
        sessionId: string;
        reason: string;
    }

    export const type = new RequestType<Params, void, void>('console/requestFullState');
}

export namespace ClearOutputNotification {

    export interface Params {
        sessionId: string;
        reason?: 'user' | 'runtime';
    }

    export const type = new NotificationType<Params>('console/clear');
}

export namespace RevealExecutionNotification {

    export interface Params {
        executionId: string;
        sessionId?: string;
    }

    export const type = new NotificationType<Params>('console/revealExecution');
}

export namespace FocusInputNotification {

    export interface Params {
        sessionId: string;
    }

    export const type = new NotificationType<Params>('console/focusInput');
}

export namespace PasteTextNotification {

    export interface Params {
        sessionId: string;
        text: string;
    }

    export const type = new NotificationType<Params>('console/pasteText');
}

export namespace SelectAllNotification {

    export interface Params {
        sessionId: string;
    }

    export const type = new NotificationType<Params>('console/selectAll');
}

export namespace NavigateInputHistoryUpNotification {

    export interface Params {
        sessionId: string;
        usingPrefixMatch: boolean;
    }

    export const type = new NotificationType<Params>('console/historyNavigateUp');
}

export namespace NavigateInputHistoryDownNotification {

    export interface Params {
        sessionId: string;
    }

    export const type = new NotificationType<Params>('console/historyNavigateDown');
}

export namespace ClearInputHistoryNotification {

    export interface Params {
        sessionId: string;
    }

    export const type = new NotificationType<Params>('console/historyClear');
}

export namespace SetPendingCodeNotification {

    export interface Params {
        sessionId: string;
        code?: string;
    }

    export const type = new NotificationType<Params>('console/setPendingCode');
}

export namespace PendingInputChangedNotification {

    export interface Params {
        sessionId: string;
        code?: string;
        inputPrompt: string;
    }

    export const type = new NotificationType<Params>('console/pendingInputChanged');
}

export namespace ConsoleSettingsChangedNotification {

    export const type = new NotificationType<ConsoleSettings>('console/settingsChanged');
}

export namespace ConsoleThemeChangedNotification {

    export interface Params {
        theme: ConsoleThemeData;
    }

    export const type = new NotificationType<Params>('console/themeChanged');
}

export namespace LanguageSupportAssetsChangedNotification {

    export interface Params {
        modules: Record<string, string>;
        grammars: Record<string, { scopeName: string; grammarUrl: string }>;
    }

    export const type = new NotificationType<Params>('console/languageSupportAssetsChanged');
}

export namespace HistoryAddNotification {

    export interface Params {
        sessionId: string;
        input: string;
        when?: number;
    }

    export const type = new NotificationType<Params>('console/historyAdd');
}

export namespace ResourceUsageNotification {

    export interface Params {
        sessionId: string;
        usage: RuntimeResourceUsage;
    }

    export const type = new NotificationType<Params>('console/resourceUsage');
}

export namespace ReplyPromptRequest {

    export interface Params {
        id: string;
        value: string;
        sessionId?: string;
    }

    export const type = new RequestType<Params, void, void>('console/replyPrompt');
}

export namespace RuntimeStartupPhaseNotification {

    export interface RuntimeStartupEvent {
        runtimeName: string;
        languageName: string;
        base64EncodedIconSvg?: string;
        newSession: boolean;
    }

    export interface Params {
        phase: 'initializing' | 'awaitingTrust' | 'reconnecting' | 'starting' | 'discovering' | 'complete';
        discoveredCount?: number;
        runtimeStartupEvent?: RuntimeStartupEvent;
    }

    export const type = new NotificationType<Params>('console/runtimeStartupPhase');
}

export interface SerializedConsoleState {
    version: number;
    items: unknown[];
    inputHistory: string[];
    trace: boolean;
    wordWrap: boolean;
    inputPrompt?: string;
    continuationPrompt?: string;
    workingDirectory?: string | null;
}

export namespace ConsoleRestoreStateNotification {

    export interface Params {
        sessionId: string;
        syncSeq: number;
        state: SerializedConsoleState;
    }

    export const type = new NotificationType<Params>('console/restoreState');
}

export namespace ConsoleSessionMetadataChangedNotification {

    export interface Params {
        sessionId: string;
        syncSeq: number;
        trace?: boolean;
        wordWrap?: boolean;
        inputPrompt?: string;
        continuationPrompt?: string;
        workingDirectory?: string | null;
    }

    export const type = new NotificationType<Params>('console/sessionMetadataChanged');
}

export namespace ConsoleRuntimeChangesNotification {

    export interface Params {
        sessionId: string;
        syncSeq: number;
        changes: ConsoleRuntimeChange[];
    }

    export const type = new NotificationType<Params>('console/runtimeChanges');
}

export namespace ConsoleReadyNotification {

    export const type = new NotificationType<void>('console/ready');
}

export namespace SetConsoleWidthNotification {

    export interface Params {
        widthInChars: number;
        sessionId?: string;
    }

    export const type = new NotificationType<Params>('console/setWidthInChars');
}

export namespace ConsoleOpenExternalNotification {

    export interface Params {
        url: string;
    }

    export const type = new NotificationType<Params>('console/openExternal');
}
