/*---------------------------------------------------------------------------------------------
 *  AUTO-GENERATED from contracts/dataExplorer.json. Do not edit this file directly.
 *--------------------------------------------------------------------------------------------*/

import { NotificationType } from 'vscode-jsonrpc';

export namespace DataExplorerReadyNotification {

    export const type = new NotificationType<void>('dataExplorer/ready');
}

export namespace DataExplorerCloseNotification {

    export const type = new NotificationType<void>('dataExplorer/close');
}

export namespace DataExplorerRequestDataNotification {

    export interface Params {
        startRow: number;
        endRow: number;
        columns?: number[];
    }

    export const type = new NotificationType<Params>('dataExplorer/requestData');
}

export namespace DataExplorerRequestSchemaNotification {

    export interface Params {
        columns: number[];
    }

    export const type = new NotificationType<Params>('dataExplorer/requestSchema');
}

export namespace DataExplorerSearchSchemaNotification {

    export interface Params {
        text: string;
        sortOrder: string;
        pinnedColumns?: number[];
        requestId?: number;
    }

    export const type = new NotificationType<Params>('dataExplorer/searchSchema');
}

export namespace DataExplorerRequestColumnProfilesNotification {

    export interface Params {
        columnIndices: number[];
        expandedColumnIndices?: number[];
        requestId?: number;
    }

    export const type = new NotificationType<Params>('dataExplorer/requestColumnProfiles');
}

export namespace DataExplorerRefreshNotification {

    export const type = new NotificationType<void>('dataExplorer/refresh');
}

export namespace DataExplorerSortNotification {

    export interface Params {
        sortKeys: Array<{ columnIndex: number; ascending: boolean }>;
    }

    export const type = new NotificationType<Params>('dataExplorer/sort');
}

export namespace DataExplorerClearSortNotification {

    export const type = new NotificationType<void>('dataExplorer/clearSort');
}

export namespace DataExplorerClearFiltersNotification {

    export const type = new NotificationType<void>('dataExplorer/clearFilters');
}

export namespace DataExplorerAddFilterNotification {

    export interface Params {
        filter: unknown;
    }

    export const type = new NotificationType<Params>('dataExplorer/addFilter');
}

export namespace DataExplorerUpdateFilterNotification {

    export interface Params {
        filter: unknown;
    }

    export const type = new NotificationType<Params>('dataExplorer/updateFilter');
}

export namespace DataExplorerRemoveFilterNotification {

    export interface Params {
        filterId: string;
    }

    export const type = new NotificationType<Params>('dataExplorer/removeFilter');
}

export namespace DataExplorerCopyToClipboardNotification {

    export interface Params {
        selectionType: 'cell' | 'cells' | 'columns' | 'rows';
        columnIndex?: number;
        rowIndex?: number;
        columnIndexes?: number[];
        rowIndexes?: number[];
    }

    export const type = new NotificationType<Params>('dataExplorer/copyToClipboard');
}

export namespace DataExplorerCopyTableDataNotification {

    export const type = new NotificationType<void>('dataExplorer/copyTableData');
}

export namespace DataExplorerExportDataNotification {

    export interface Params {
        format: 'tsv' | 'csv';
    }

    export const type = new NotificationType<Params>('dataExplorer/exportData');
}

export namespace DataExplorerMoveToNewWindowNotification {

    export const type = new NotificationType<void>('dataExplorer/moveToNewWindow');
}

export namespace DataExplorerConvertToCodeNotification {

    export interface Params {
        suggestedSyntax?: string;
        availableSyntaxes?: string[];
    }

    export const type = new NotificationType<Params>('dataExplorer/convertToCode');
}

export namespace DataExplorerOpenAsPlaintextNotification {

    export const type = new NotificationType<void>('dataExplorer/openAsPlaintext');
}

export namespace DataExplorerToggleFileOptionsNotification {

    export interface Params {
        hasHeaderRow?: boolean;
        supportsFileOptions?: boolean;
    }

    export const type = new NotificationType<Params>('dataExplorer/toggleFileOptions');
}

export namespace DataExplorerRunConvertToCodeNotification {

    export interface Params {
        desiredSyntax: string;
    }

    export const type = new NotificationType<Params>('dataExplorer/runConvertToCode');
}

export namespace DataExplorerApplyFileOptionsNotification {

    export interface Params {
        hasHeaderRow: boolean;
    }

    export const type = new NotificationType<Params>('dataExplorer/applyFileOptions');
}

export namespace DataExplorerRequestConvertToCodePreviewNotification {

    export interface Params {
        desiredSyntax: string;
        requestId: number;
    }

    export const type = new NotificationType<Params>('dataExplorer/requestConvertToCodePreview');
}

export namespace DataExplorerSetLayoutNotification {

    export interface Params {
        layout: 'SummaryOnLeft' | 'SummaryOnRight';
    }

    export const type = new NotificationType<Params>('dataExplorer/setLayout');
}

export namespace DataExplorerSetSummaryCollapsedNotification {

    export interface Params {
        collapsed: boolean;
    }

    export const type = new NotificationType<Params>('dataExplorer/setSummaryCollapsed');
}

export namespace DataExplorerFocusChangedNotification {

    export interface Params {
        focused: boolean;
    }

    export const type = new NotificationType<Params>('dataExplorer/focusChanged');
}

export namespace DataExplorerCopyNotification {

    export const type = new NotificationType<void>('dataExplorer/copy');
}

export namespace DataExplorerShowColumnContextMenuNotification {

    export const type = new NotificationType<void>('dataExplorer/showColumnContextMenu');
}

export namespace DataExplorerShowRowContextMenuNotification {

    export const type = new NotificationType<void>('dataExplorer/showRowContextMenu');
}

export namespace DataExplorerShowCellContextMenuNotification {

    export const type = new NotificationType<void>('dataExplorer/showCellContextMenu');
}

export namespace DataExplorerLayoutChangedNotification {

    export interface Params {
        layout: 'SummaryOnLeft' | 'SummaryOnRight';
    }

    export const type = new NotificationType<Params>('dataExplorer/layoutChanged');
}

export namespace DataExplorerSummaryCollapsedChangedNotification {

    export interface Params {
        collapsed: boolean;
    }

    export const type = new NotificationType<Params>('dataExplorer/summaryCollapsedChanged');
}

export namespace DataExplorerConvertToCodePreviewNotification {

    export interface Params {
        desiredSyntax: string;
        requestId: number;
        code: string;
        error?: string;
    }

    export const type = new NotificationType<Params>('dataExplorer/convertToCodePreview');
}

export namespace DataExplorerInitializeNotification {

    export interface Params {
        identifier: string;
        displayName: string;
        languageName: string;
        backendState: unknown | null;
    }

    export const type = new NotificationType<Params>('dataExplorer/initialize');
}

export namespace DataExplorerMetadataNotification {

    export interface Params {
        displayName: string;
        numRows: number;
        numColumns: number;
        hasRowLabels?: boolean;
    }

    export const type = new NotificationType<Params>('dataExplorer/metadata');
}

export namespace DataExplorerSchemaNotification {

    export interface Params {
        columns: unknown[];
    }

    export const type = new NotificationType<Params>('dataExplorer/schema');
}

export namespace DataExplorerSummarySchemaNotification {

    export interface Params {
        columns: unknown[];
        columnIndices: number[];
        requestId?: number;
    }

    export const type = new NotificationType<Params>('dataExplorer/summarySchema');
}

export namespace DataExplorerColumnProfilesNotification {

    export interface Params {
        profiles: Array<{ columnIndex: number; profile: unknown }>;
        error?: string;
        requestId?: number;
    }

    export const type = new NotificationType<Params>('dataExplorer/columnProfiles');
}

export namespace DataExplorerDataNotification {

    export interface Params {
        columns: unknown[][];
        schema?: unknown[];
        startRow: number;
        endRow: number;
        columnIndices?: number[];
        rowLabels?: string[];
        totalRows?: number;
        totalColumns?: number;
    }

    export const type = new NotificationType<Params>('dataExplorer/data');
}

export namespace DataExplorerBackendStateNotification {

    export interface Params {
        state: unknown;
    }

    export const type = new NotificationType<Params>('dataExplorer/backendState');
}

export namespace DataExplorerLoadingNotification {

    export interface Params {
        isLoading: boolean;
    }

    export const type = new NotificationType<Params>('dataExplorer/loading');
}

export namespace DataExplorerErrorNotification {

    export interface Params {
        message: string;
    }

    export const type = new NotificationType<Params>('dataExplorer/error');
}
