/*---------------------------------------------------------------------------------------------
 *  AUTO-GENERATED from contracts/help.json. Do not edit this file directly.
 *--------------------------------------------------------------------------------------------*/

import { NotificationType } from 'vscode-jsonrpc';

export namespace HelpStateNotification {

    export interface HelpEntryState {
        sourceUrl: string;
        targetUrl: string;
        title?: string;
        scrollX: number;
        scrollY: number;
        isWelcome?: boolean;
    }

    export interface HistoryEntry {
        sourceUrl: string;
        targetUrl: string;
        title?: string;
    }

    export interface Params {
        entry?: HelpEntryState;
        history: HistoryEntry[];
        canNavigateBackward: boolean;
        canNavigateForward: boolean;
    }

    export const type = new NotificationType<Params>('help/state');
}

export namespace HelpNavigateNotification {

    export interface Params {
        url: string;
    }

    export const type = new NotificationType<Params>('help/navigate');
}

export namespace HelpNavigateBackwardNotification {

    export const type = new NotificationType<{}>('help/navigateBackward');
}

export namespace HelpNavigateForwardNotification {

    export const type = new NotificationType<{}>('help/navigateForward');
}

export namespace HelpHistoryOpenNotification {

    export interface Params {
        index: number;
    }

    export const type = new NotificationType<Params>('help/openHistory');
}

export namespace HelpShowWelcomeNotification {

    export const type = new NotificationType<{}>('help/showWelcome');
}

export namespace HelpFindNotification {

    export const type = new NotificationType<{}>('help/find');
}

export namespace HelpScrollNotification {

    export interface Params {
        scrollX: number;
        scrollY: number;
    }

    export const type = new NotificationType<Params>('help/scroll');
}

export namespace HelpCompleteNotification {

    export interface Params {
        title?: string;
    }

    export const type = new NotificationType<Params>('help/complete');
}

export namespace HelpStylesNotification {

    export interface Params {
        styles: Record<string, string | number>;
    }

    export const type = new NotificationType<Params>('help/styles');
}

export namespace HelpExecuteCommandNotification {

    export interface Params {
        command: string;
    }

    export const type = new NotificationType<Params>('help/executeCommand');
}

export namespace HelpCopySelectionNotification {

    export interface Params {
        selection?: string;
    }

    export const type = new NotificationType<Params>('help/copySelection');
}

export namespace HelpThemeChangedNotification {

    export const type = new NotificationType<{}>('help/themeChanged');
}
