/*---------------------------------------------------------------------------------------------
 *  AUTO-GENERATED from contracts/lsp.json. Do not edit this file directly.
 *--------------------------------------------------------------------------------------------*/

import { RequestType } from 'vscode-jsonrpc';

export interface LspPosition {
    line: number;
    character: number;
}

export interface LspRange {
    start: LspPosition;
    end: LspPosition;
}

export interface LspMarkupContent {
    kind: 'plaintext' | 'markdown';
    value: string;
}

export enum LspCompletionItemKind {
    Text = 1,
    Method = 2,
    Function = 3,
    Constructor = 4,
    Field = 5,
    Variable = 6,
    Class = 7,
    Interface = 8,
    Module = 9,
    Property = 10,
    Unit = 11,
    Value = 12,
    Enum = 13,
    Keyword = 14,
    Snippet = 15,
    Color = 16,
    File = 17,
    Reference = 18,
    Folder = 19,
    Constant = 21,
    Operator = 24,
}

export interface LspCompletionItem {
    label: string;
    kind?: LspCompletionItemKind;
    detail?: string;
    documentation?: string | LspMarkupContent;
    insertText?: string;
    filterText?: string;
    sortText?: string;
}

export interface LspParameterInformation {
    label: string | [number, number];
    documentation?: string | LspMarkupContent;
}

export interface LspSignatureInformation {
    label: string;
    documentation?: string | LspMarkupContent;
    parameters?: LspParameterInformation[];
    activeParameter?: number;
}

export namespace LspCompletionRequest {

    export interface Params {
        sessionId: string;
        code: string;
        position: LspPosition;
    }

    export interface Result {
        items: LspCompletionItem[];
        isIncomplete?: boolean;
    }

    export const type = new RequestType<Params, Result, void>('lsp/completion');
}

export namespace LspHoverRequest {

    export interface Params {
        sessionId: string;
        code: string;
        position: LspPosition;
    }

    export interface Result {
        contents: LspMarkupContent | string;
        range?: LspRange;
    }

    export const type = new RequestType<Params, Result | null, void>('lsp/hover');
}

export namespace LspSignatureHelpRequest {

    export interface Params {
        sessionId: string;
        code: string;
        position: LspPosition;
    }

    export interface Result {
        signatures: LspSignatureInformation[];
        activeSignature?: number;
        activeParameter?: number;
    }

    export const type = new RequestType<Params, Result | null, void>('lsp/signatureHelp');
}
