/*---------------------------------------------------------------------------------------------
 *  AUTO-GENERATED from contracts/plots.json. Do not edit this file directly.
 *--------------------------------------------------------------------------------------------*/

import { NotificationType, RequestType } from 'vscode-jsonrpc';

export interface PlotData {
    data: string;
    mimeType: string;
}

export namespace RenderPlotRequest {

    export interface Params {
        plotId: string;
        width: number;
        height: number;
        format: 'png' | 'svg';
        pixelRatio?: number;
    }

    export interface Result {
        data: string;
        mimeType: string;
        renderVersion: number;
    }

    export const type = new RequestType<Params, Result, void>('plots/render');
}

export namespace ClaimHtmlPlotRequest {

    export interface Params {
        plotId: string;
    }

    export interface Result {
        success: boolean;
        error?: string;
    }

    export const type = new RequestType<Params, Result, void>('plots/claimHtmlPlot');
}

export namespace ReleaseHtmlPlotRequest {

    export interface Params {
        plotId: string;
    }

    export interface Result {
        success: boolean;
        error?: string;
    }

    export const type = new RequestType<Params, Result, void>('plots/releaseHtmlPlot');
}

export namespace HtmlPlotLayoutNotification {

    export interface Params {
        plotId: string;
        width: number;
        height: number;
    }

    export const type = new NotificationType<Params>('plots/layoutHtmlPlot');
}

export namespace PlotAddedNotification {

    export interface Params {
        plotId: string;
        thumbnail?: string;
        initialData?: string;
        initialRenderSettings?: { width: number; height: number; pixelRatio: number; };
        renderVersion?: number;
        sessionId?: string;
        kind?: 'static' | 'dynamic' | 'html';
        htmlUri?: string;
        originUri?: string;
        name?: string;
        code?: string;
        parentId?: string;
        languageId?: string;
        zoomLevel?: number;
        sizingPolicyId?: string;
        customSize?: { width: number; height: number; };
        hasIntrinsicSize?: boolean;
    }

    export const type = new NotificationType<Params>('plots/added');
}

export namespace SelectPlotZoomRequest {

    export interface Params {
        plotId: string;
        zoomLevel: number;
    }

    export const type = new RequestType<Params, void, void>('plots/selectZoom');
}

export namespace PlotZoomChangedNotification {

    export interface Params {
        plotId: string;
        zoomLevel: number;
    }

    export const type = new NotificationType<Params>('plots/zoomChanged');
}

export namespace PlotViewportChangedNotification {

    export interface Params {
        width: number;
        height: number;
        pixelRatio: number;
        format: 'png' | 'svg';
    }

    export const type = new NotificationType<Params>('plots/viewportChanged');
}

export enum PlotClientState {
    Unrendered = 'unrendered',
    RenderPending = 'render_pending',
    Rendering = 'rendering',
    Rendered = 'rendered',
    Closed = 'closed',
}

export interface SizingPolicyInfo {
    id: string;
    name: string;
}

export interface IntrinsicSize {
    width: number;
    height: number;
    unit: 'inches' | 'pixels';
}

export namespace GetSizingPoliciesRequest {

    export interface Result {
        policies: SizingPolicyInfo[];
        selectedPolicyId: string;
    }

    export const type = new RequestType<void, Result, void>('plots/getSizingPolicies');
}

export namespace SelectSizingPolicyRequest {

    export interface Params {
        policyId: string;
    }

    export const type = new RequestType<Params, void, void>('plots/selectSizingPolicy');
}

export namespace SetCustomSizeRequest {

    export interface Params {
        width: number;
        height: number;
    }

    export const type = new RequestType<Params, void, void>('plots/setCustomSize');
}

export namespace ClearCustomSizeRequest {

    export const type = new RequestType<void, void, void>('plots/clearCustomSize');
}

export namespace GetIntrinsicSizeRequest {

    export interface Params {
        plotId: string;
    }

    export interface Result {
        intrinsicSize?: IntrinsicSize;
    }

    export const type = new RequestType<Params, Result, void>('plots/getIntrinsicSize');
}

export namespace GetPlotStateRequest {

    export interface Params {
        plotId: string;
    }

    export interface Result {
        state: PlotClientState;
        renderEstimateMs: number;
    }

    export const type = new RequestType<Params, Result, void>('plots/getPlotState');
}

export namespace GetHistoryStateRequest {

    export interface Result {
        policy: 'always' | 'never' | 'automatic';
        position: 'auto' | 'bottom' | 'right';
    }

    export const type = new RequestType<void, Result, void>('plots/getHistoryState');
}

export namespace SelectHistoryPolicyRequest {

    export interface Params {
        policy: 'always' | 'never' | 'automatic';
    }

    export const type = new RequestType<Params, void, void>('plots/selectHistoryPolicy');
}

export namespace SelectHistoryPositionRequest {

    export interface Params {
        position: 'auto' | 'bottom' | 'right';
    }

    export const type = new RequestType<Params, void, void>('plots/selectHistoryPosition');
}

export namespace HistoryPolicyChangedNotification {

    export interface Params {
        policy: 'always' | 'never' | 'automatic';
    }

    export const type = new NotificationType<Params>('plots/historyPolicyChanged');
}

export namespace HistoryPositionChangedNotification {

    export interface Params {
        position: 'auto' | 'bottom' | 'right';
    }

    export const type = new NotificationType<Params>('plots/historyPositionChanged');
}

export namespace GetDarkFilterModeRequest {

    export interface Result {
        mode: 'on' | 'off' | 'auto';
    }

    export const type = new RequestType<void, Result, void>('plots/getDarkFilterMode');
}

export namespace SelectDarkFilterModeRequest {

    export interface Params {
        mode: 'on' | 'off' | 'auto';
    }

    export const type = new RequestType<Params, void, void>('plots/selectDarkFilterMode');
}

export namespace DarkFilterModeChangedNotification {

    export interface Params {
        mode: 'on' | 'off' | 'auto';
    }

    export const type = new NotificationType<Params>('plots/darkFilterModeChanged');
}

export namespace SizingPolicyChangedNotification {

    export interface Params {
        plotId?: string;
        policyId: string;
        policyName: string;
        policies?: SizingPolicyInfo[];
        customSize?: { width: number; height: number; };
    }

    export const type = new NotificationType<Params>('plots/sizingPolicyChanged');
}

export namespace PlotStateChangedNotification {

    export interface Params {
        plotId: string;
        state: PlotClientState;
    }

    export const type = new NotificationType<Params>('plots/plotStateChanged');
}

export namespace PlotRenderCompletedNotification {

    export interface Params {
        plotId: string;
        uri?: string;
        renderTimeMs: number;
        renderVersion: number;
    }

    export const type = new NotificationType<Params>('plots/renderCompleted');
}

export namespace IntrinsicSizeReceivedNotification {

    export interface Params {
        plotId: string;
        intrinsicSize: IntrinsicSize;
    }

    export const type = new NotificationType<Params>('plots/intrinsicSizeReceived');
}

export namespace PlotUpdatedNotification {

    export interface Params {
        plotId: string;
        name?: string;
        code?: string;
        parentId?: string;
        languageId?: string;
        originUri?: string;
    }

    export const type = new NotificationType<Params>('plots/updated');
}

export namespace PlotsReadyNotification {

    export const type = new NotificationType<void>('plots/ready');
}

export interface PlotEmittedInfo {
    id: string;
    sessionId: string;
    code?: string;
}

export namespace PlotEmittedNotification {

    export interface Params {
        plot: PlotEmittedInfo;
    }

    export const type = new NotificationType<Params>('plots/emitted');
}

export namespace SelectedPlotChangedNotification {

    export interface Params {
        plotId?: string;
        selectedSizingPolicyId?: string;
        sizingPolicies?: SizingPolicyInfo[];
        customSize?: { width: number; height: number; };
        hasIntrinsicSize?: boolean;
        zoomLevel?: number;
    }

    export const type = new NotificationType<Params>('plots/selectedChanged');
}

export namespace SelectPlotRequest {

    export interface Params {
        plotId: string;
    }

    export const type = new RequestType<Params, void, void>('plots/select');
}

export namespace RemovePlotRequest {

    export interface Params {
        plotId: string;
    }

    export const type = new RequestType<Params, void, void>('plots/remove');
}
