/*---------------------------------------------------------------------------------------------
 *  AUTO-GENERATED from contracts/plotEditor.json. Do not edit this file directly.
 *--------------------------------------------------------------------------------------------*/

import { NotificationType } from 'vscode-jsonrpc';

export namespace PlotEditorReadyNotification {

    export const type = new NotificationType<void>('plotEditor/ready');
}

export namespace PlotEditorRenderNotification {

    export interface Params {
        width: number;
        height: number;
        pixelRatio: number;
        format: 'png' | 'svg';
    }

    export const type = new NotificationType<Params>('plotEditor/render');
}

export namespace PlotEditorSaveNotification {

    export const type = new NotificationType<void>('plotEditor/save');
}

export namespace PlotEditorCopyNotification {

    export const type = new NotificationType<void>('plotEditor/copy');
}

export namespace PlotEditorCloseNotification {

    export const type = new NotificationType<void>('plotEditor/close');
}

export namespace PlotEditorSetImageNotification {

    export interface Params {
        data: string;
    }

    export const type = new NotificationType<Params>('plotEditor/setImage');
}

export namespace PlotEditorRenderResultNotification {

    export interface Params {
        data: string;
        mimeType: string;
    }

    export const type = new NotificationType<Params>('plotEditor/renderResult');
}
