/*---------------------------------------------------------------------------------------------
 *  AUTO-GENERATED from contracts/session.json. Do not edit this file directly.
 *--------------------------------------------------------------------------------------------*/

import { NotificationType, RequestType } from 'vscode-jsonrpc';

export interface SessionInfo {
    id: string;
    name: string;
    runtimeName: string;
    state: 'uninitialized' | 'starting' | 'ready' | 'busy' | 'offline' | 'interrupting' | 'restarting' | 'exiting' | 'exited' | 'disconnected';
    runtimePath?: string;
    runtimeVersion?: string;
    runtimeSource?: string;
    base64EncodedIconSvg?: string;
    promptActive: boolean;
    runtimeAttached: boolean;
}

export namespace ListSessionsRequest {

    export interface Result {
        sessions: SessionInfo[];
        activeSessionId?: string;
    }

    export const type = new RequestType<void, Result, void>('session/list');
}

export namespace CreateSessionRequest {

    export interface Params {
        name?: string;
        showRuntimePicker?: boolean;
    }

    export interface Result {
        session?: SessionInfo;
    }

    export const type = new RequestType<Params, Result, void>('session/create');
}

export namespace StopSessionRequest {

    export interface Params {
        sessionId: string;
    }

    export const type = new RequestType<Params, void, void>('session/stop');
}

export namespace RestartSessionRequest {

    export interface Params {
        sessionId: string;
    }

    export const type = new RequestType<Params, void, void>('session/restart');
}

export namespace SwitchSessionRequest {

    export interface Params {
        sessionId: string;
    }

    export const type = new RequestType<Params, void, void>('session/switch');
}

export namespace RenameSessionRequest {

    export interface Params {
        sessionId: string;
        newName: string;
    }

    export const type = new RequestType<Params, void, void>('session/rename');
}

export namespace ListOutputChannelsRequest {

    export interface Params {
        sessionId: string;
    }

    export interface Result {
        channels: ('console' | 'kernel' | 'lsp')[];
    }

    export const type = new RequestType<Params, Result, void>('session/listOutputChannels');
}

export namespace ShowOutputChannelRequest {

    export interface Params {
        sessionId: string;
        channel: 'console' | 'kernel' | 'lsp';
    }

    export const type = new RequestType<Params, void, void>('session/showOutputChannel');
}

export namespace SessionInfoNotification {

    export interface Params {
        sessions: SessionInfo[];
        activeSessionId?: string;
    }

    export const type = new NotificationType<Params>('session/info');
}
