/*---------------------------------------------------------------------------------------------
 *  AUTO-GENERATED from contracts/variables.json. Do not edit this file directly.
 *--------------------------------------------------------------------------------------------*/

import { NotificationType, RequestType } from 'vscode-jsonrpc';

export interface Variable {
    name: string;
    path: string[];
    type: string;
    value: string;
    size?: number;
    hasChildren: boolean;
    kind?: string;
    hasViewer?: boolean;
}

export namespace ListVariablesRequest {

    export interface Params {
        sessionId?: string;
    }

    export interface Result {
        variables: Variable[];
    }

    export const type = new RequestType<Params, Result, void>('variables/list');
}

export namespace InspectVariableRequest {

    export interface Params {
        path: string[];
        sessionId?: string;
    }

    export interface Result {
        children: Variable[];
        length?: number;
    }

    export const type = new RequestType<Params, Result, void>('variables/inspect');
}

export namespace SetActiveVariablesSessionRequest {

    export interface Params {
        sessionId: string;
    }

    export const type = new RequestType<Params, void, void>('variables/setActiveSession');
}

export namespace VariablesUpdateNotification {

    export interface Params {
        assigned: Variable[];
        removed: string[];
        sessionId?: string;
    }

    export const type = new NotificationType<Params>('variables/update');
}

export namespace VariablesReadyNotification {

    export const type = new NotificationType<void>('variables/ready');
}

export interface VariablesInstanceInfo {
    sessionId: string;
    state: 'uninitialized' | 'opening' | 'connected' | 'closing' | 'closed';
    status: 'idle' | 'busy' | 'disconnected';
    grouping: 'none' | 'kind' | 'size';
    sorting: 'name' | 'size' | 'recent';
    filterText: string;
    highlightRecent: boolean;
}

export namespace VariablesInstanceStartedNotification {

    export interface Params {
        instance: VariablesInstanceInfo;
    }

    export const type = new NotificationType<Params>('variables/instanceStarted');
}

export namespace VariablesInstanceStoppedNotification {

    export interface Params {
        sessionId: string;
    }

    export const type = new NotificationType<Params>('variables/instanceStopped');
}

export namespace ActiveVariablesInstanceChangedNotification {

    export interface Params {
        sessionId?: string;
    }

    export const type = new NotificationType<Params>('variables/activeInstanceChanged');
}

export interface VariableEntry {
    type: 'group' | 'item' | 'overflow';
    id?: string;
    title?: string;
    isExpanded?: boolean;
    indentLevel?: number;
    path?: string[];
    displayName?: string;
    displayValue?: string;
    displayType?: string;
    size?: number;
    kind?: string;
    hasChildren?: boolean;
    hasViewer?: boolean;
    isRecent?: boolean;
    overflowValues?: number;
}

export namespace VariableEntriesChangedNotification {

    export interface Params {
        sessionId: string;
        entries: VariableEntry[];
    }

    export const type = new NotificationType<Params>('variables/entriesChanged');
}

export namespace ListVariableEntriesRequest {

    export interface Params {
        sessionId?: string;
    }

    export interface Result {
        entries: VariableEntry[];
    }

    export const type = new RequestType<Params, Result, void>('variables/listEntries');
}

export namespace ExpandVariableGroupRequest {

    export interface Params {
        groupId: string;
        sessionId?: string;
    }

    export const type = new RequestType<Params, void, void>('variables/expandGroup');
}

export namespace CollapseVariableGroupRequest {

    export interface Params {
        groupId: string;
        sessionId?: string;
    }

    export const type = new RequestType<Params, void, void>('variables/collapseGroup');
}

export namespace ExpandVariableItemRequest {

    export interface Params {
        path: string[];
        sessionId?: string;
    }

    export const type = new RequestType<Params, void, void>('variables/expandItem');
}

export namespace CollapseVariableItemRequest {

    export interface Params {
        path: string[];
        sessionId?: string;
    }

    export const type = new RequestType<Params, void, void>('variables/collapseItem');
}

export namespace SetVariablesGroupingRequest {

    export interface Params {
        grouping: 'none' | 'kind' | 'size';
    }

    export const type = new RequestType<Params, void, void>('variables/setGrouping');
}

export namespace SetVariablesSortingRequest {

    export interface Params {
        sorting: 'name' | 'size' | 'recent';
    }

    export const type = new RequestType<Params, void, void>('variables/setSorting');
}

export namespace SetVariablesFilterRequest {

    export interface Params {
        filterText: string;
    }

    export const type = new RequestType<Params, void, void>('variables/setFilter');
}

export namespace SetVariablesHighlightRecentRequest {

    export interface Params {
        highlightRecent: boolean;
    }

    export const type = new RequestType<Params, void, void>('variables/setHighlightRecent');
}
