/*---------------------------------------------------------------------------------------------
 *  AUTO-GENERATED from contracts/viewer.json. Do not edit this file directly.
 *--------------------------------------------------------------------------------------------*/

import { NotificationType } from 'vscode-jsonrpc';

export namespace ViewerShowNotification {

    export interface Params {
        url: string;
        title?: string;
        height?: number;
        sessionId?: string;
        kind?: 'url' | 'html';
    }

    export const type = new NotificationType<Params>('viewer/show');
}
